In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import math 
import time 
import os
import sys 
import pathlib

In [2]:
df = pd.read_csv("/home/dhruv/Documents/NCF/NCF_Recommendation/NCF_Pytorch/train_data.csv")
df.head()

   UserID  ItemID  Rating  Timestamp
0       0      32       4  978824330
1       0      34       4  978824330
2       0       4       5  978824291
3       0      35       4  978824291
4       0      30       4  978824291

In [3]:
new_df = df.groupby("UserID").count().reset_index()
new_df

      UserID  ItemID  Rating  Timestamp
0          0      52      52         52
1          1     128     128        128
2          2      50      50         50
3          3      20      20         20
4          4     197     197        197
...      ...     ...     ...        ...
6035    6035     887     887        887
6036    6036     201     201        201
6037    6037      19      19         19
6038    6038     122     122        122
6039    6039     340     340        340

[6040 rows x 4 columns]

In [4]:
new_df["ItemID"].max()

np.int64(2313)

In [5]:
new_df.sort_values(["UserID", "Timestamp"])

      UserID  ItemID  Rating  Timestamp
0          0      52      52         52
1          1     128     128        128
2          2      50      50         50
3          3      20      20         20
4          4     197     197        197
...      ...     ...     ...        ...
6035    6035     887     887        887
6036    6036     201     201        201
6037    6037      19      19         19
6038    6038     122     122        122
6039    6039     340     340        340

[6040 rows x 4 columns]

# Generate all the negative items for each user and save the data

In [1]:
import pandas as pd
import random
from tqdm import tqdm

In [2]:

df = pd.read_csv("/home/dhruv/Documents/NCF/NCF_Recommendation/NCF_Pytorch/train_data.csv")
# Columns: user_id, item_id, rating
df.head(5)

   UserID  ItemID  Rating  Timestamp
0       0      32       4  978824330
1       0      34       4  978824330
2       0       4       5  978824291
3       0      35       4  978824291
4       0      30       4  978824291

In [14]:
all_users = df['UserID'].unique().tolist()
all_items = df['ItemID'].unique().tolist()

all_users, all_items

([0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  218,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  300,
  301,
  302,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  375,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384,
  385,
  386,
  387,
  388,
  389,
  390,
  391,
  392,
  393,
  394,
  395,
  396,
  397,
  398,
  399,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  436,
  437,
  438,
  439,
  440,
  441,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  456,
  457,
  458,
  459,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499,
  500,
  501,
  502,
  503,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  513,
  514,
  515,
  516,
  517,
  518,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550,
  551,
  552,
  553,
  554,
  555,
  556,
  557,
  558,
  559,
  560,
  561,
  562,
  563,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  579,
  580,
  581,
  582,
  583,
  584,
  585,
  586,
  587,
  588,
  589,
  590,
  591,
  592,
  593,
  594,
  595,
  596,
  597,
  598,
  599,
  600,
  601,
  602,
  603,
  604,
  605,
  606,
  607,
  608,
  609,
  610,
  611,
  612,
  613,
  614,
  615,
  616,
  617,
  618,
  619,
  620,
  621,
  622,
  623,
  624,
  625,
  626,
  627,
  628,
  629,
  630,
  631,
  632,
  633,
  634,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  648,
  649,
  650,
  651,
  652,
  653,
  654,
  655,
  656,
  657,
  658,
  659,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  667,
  668,
  669,
  670,
  671,
  672,
  673,
  674,
  675,
  676,
  677,
  678,
  679,
  680,
  681,
  682,
  683,
  684,
  685,
  686,
  687,
  688,
  689,
  690,
  691,
  692,
  693,
  694,
  695,
  696,
  697,
  698,
  699,
  700,
  701,
  702,
  703,
  704,
  705,
  706,
  707,
  708,
  709,
  710,
  711,
  712,
  713,
  714,
  715,
  716,
  717,
  718,
  719,
  720,
  721,
  722,
  723,
  724,
  725,
  726,
  727,
  728,
  729,
  730,
  731,
  732,
  733,
  734,
  735,
  736,
  737,
  738,
  739,
  740,
  741,
  742,
  743,
  744,
  745,
  746,
  747,
  748,
  749,
  750,
  751,
  752,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
  774,
  775,
  776,
  777,
  778,
  779,
  780,
  781,
  782,
  783,
  784,
  785,
  786,
  787,
  788,
  789,
  790,
  791,
  792,
  793,
  794,
  795,
  796,
  797,
  798,
  799,
  800,
  801,
  802,
  803,
  804,
  805,
  806,
  807,
  808,
  809,
  810,
  811,
  812,
  813,
  814,
  815,
  816,
  817,
  818,
  819,
  820,
  821,
  822,
  823,
  824,
  825,
  826,
  827,
  828,
  829,
  830,
  831,
  832,
  833,
  834,
  835,
  836,
  837,
  838,
  839,
  840,
  841,
  842,
  843,
  844,
  845,
  846,
  847,
  848,
  849,
  850,
  851,
  852,
  853,
  854,
  855,
  856,
  857,
  858,
  859,
  860,
  861,
  862,
  863,
  864,
  865,
  866,
  867,
  868,
  869,
  870,
  871,
  872,
  873,
  874,
  875,
  876,
  877,
  878,
  879,
  880,
  881,
  882,
  883,
  884,
  885,
  886,
  887,
  888,
  889,
  890,
  891,
  892,
  893,
  894,
  895,
  896,
  897,
  898,
  899,
  900,
  901,
  902,
  903,
  904,
  905,
  906,
  907,
  908,
  909,
  910,
  911,
  912,
  913,
  914,
  915,
  916,
  917,
  918,
  919,
  920,
  921,
  922,
  923,
  924,
  925,
  926,
  927,
  928,
  929,
  930,
  931,
  932,
  933,
  934,
  935,
  936,
  937,
  938,
  939,
  940,
  941,
  942,
  943,
  944,
  945,
  946,
  947,
  948,
  949,
  950,
  951,
  952,
  953,
  954,
  955,
  956,
  957,
  958,
  959,
  960,
  961,
  962,
  963,
  964,
  965,
  966,
  967,
  968,
  969,
  970,
  971,
  972,
  973,
  974,
  975,
  976,
  977,
  978,
  979,
  980,
  981,
  982,
  983,
  984,
  985,
  986,
  987,
  988,
  989,
  990,
  991,
  992,
  993,
  994,
  995,
  996,
  997,
  998,
  999,
  ...],
 [32,
  34,
  4,
  35,
  30,
  29,
  33,
  40,
  10,
  16,
  23,
  28,
  12,
  8,
  5,
  20,
  46,
  15,
  50,
  49,
  13,
  1,
  52,
  38,
  19,
  6,
  2,
  26,
  17,
  39,
  45,
  42,
  14,
  11,
  18,
  48,
  41,
  43,
  51,
  9,
  44,
  21,
  0,
  47,
  7,
  3,
  36,
  24,
  22,
  37,
  27,
  31,
  86,
  66,
  72,
  130,
  73,
  79,
  126,
  163,
  91,
  98,
  60,
  137,
  107,
  118,
  154,
  146,
  69,
  74,
  83,
  160,
  157,
  94,
  65,
  125,
  119,
  58,
  122,
  117,
  93,
  120,
  166,
  150,
  155,
  90,
  145,
  110,
  78,
  113,
  62,
  156,
  148,
  144,
  97,
  151,
  132,
  75,
  138,
  116,
  171,
  129,
  134,
  88,
  55,
  173,
  142,
  161,
  152,
  56,
  141,
  89,
  57,
  114,
  59,
  102,
  169,
  80,
  172,
  140,
  112,
  170,
  81,
  77,
  123,
  108,
  109,
  54,
  68,
  100,
  121,
  158,
  61,
  82,
  162,
  168,
  84,
  164,
  139,
  96,
  99,
  135,
  95,
  111,
  153,
  136,
  143,
  124,
  53,
  85,
  174,
  92,
  115,
  76,
  149,
  147,
  106,
  103,
  63,
  128,
  159,
  67,
  101,
  104,
  70,
  167,
  105,
  165,
  87,
  131,
  64,
  71,
  127,
  179,
  182,
  198,
  176,
  183,
  190,
  199,
  175,
  177,
  184,
  206,
  180,
  202,
  193,
  191,
  200,
  205,
  187,
  195,
  185,
  192,
  189,
  188,
  186,
  201,
  204,
  197,
  196,
  203,
  194,
  181,
  178,
  210,
  209,
  211,
  217,
  212,
  215,
  216,
  213,
  214,
  274,
  356,
  329,
  254,
  331,
  375,
  251,
  260,
  344,
  378,
  261,
  347,
  249,
  289,
  288,
  319,
  330,
  228,
  370,
  235,
  264,
  314,
  292,
  265,
  373,
  296,
  303,
  304,
  325,
  255,
  302,
  353,
  322,
  310,
  361,
  238,
  300,
  252,
  382,
  313,
  324,
  343,
  240,
  323,
  226,
  369,
  371,
  328,
  312,
  225,
  357,
  335,
  351,
  224,
  233,
  358,
  362,
  326,
  256,
  232,
  346,
  242,
  229,
  316,
  290,
  284,
  320,
  285,
  337,
  364,
  366,
  374,
  367,
  221,
  376,
  333,
  318,
  348,
  299,
  379,
  281,
  342,
  245,
  283,
  301,
  383,
  282,
  247,
  220,
  239,
  269,
  309,
  276,
  272,
  381,
  365,
  339,
  297,
  253,
  298,
  275,
  271,
  230,
  355,
  258,
  280,
  384,
  295,
  227,
  262,
  259,
  306,
  336,
  244,
  257,
  266,
  246,
  377,
  234,
  241,
  267,
  293,
  270,
  349,
  237,
  218,
  223,
  279,
  286,
  307,
  305,
  243,
  350,
  263,
  250,
  332,
  359,
  311,
  248,
  294,
  287,
  308,
  338,
  345,
  334,
  341,
  291,
  273,
  219,
  340,
  268,
  317,
  327,
  315,
  363,
  354,
  278,
  231,
  380,
  372,
  352,
  360,
  368,
  277,
  236,
  321,
  400,
  387,
  429,
  405,
  406,
  413,
  393,
  407,
  394,
  416,
  397,
  408,
  410,
  402,
  403,
  414,
  388,
  426,
  25,
  390,
  389,
  421,
  412,
  415,
  401,
  398,
  422,
  427,
  399,
  391,
  385,
  423,
  419,
  386,
  425,
  404,
  428,
  424,
  207,
  409,
  411,
  418,
  417,
  395,
  420,
  392,
  430,
  432,
  433,
  431,
  434,
  468,
  440,
  467,
  443,
  441,
  452,
  511,
  450,
  492,
  481,
  449,
  480,
  436,
  458,
  474,
  455,
  503,
  513,
  489,
  471,
  466,
  459,
  487,
  446,
  501,
  472,
  465,
  473,
  448,
  494,
  447,
  508,
  507,
  451,
  482,
  445,
  442,
  488,
  502,
  454,
  438,
  490,
  485,
  510,
  496,
  463,
  456,
  477,
  505,
  461,
  439,
  479,
  475,
  462,
  460,
  509,
  453,
  478,
  444,
  491,
  483,
  500,
  435,
  484,
  506,
  437,
  470,
  498,
  464,
  469,
  504,
  493,
  222,
  512,
  457,
  495,
  476,
  497,
  499,
  486,
  528,
  550,
  518,
  525,
  396,
  534,
  548,
  521,
  520,
  523,
  527,
  542,
  538,
  529,
  536,
  537,
  515,
  543,
  540,
  549,
  524,
  539,
  544,
  532,
  526,
  522,
  516,
  541,
  533,
  519,
  547,
  535,
  546,
  517,
  545,
  530,
  531,
  672,
  610,
  661,
  589,
  620,
  658,
  697,
  564,
  574,
  612,
  631,
  773,
  670,
  559,
  611,
  632,
  629,
  595,
  716,
  705,
  752,
  722,
  562,
  701,
  597,
  648,
  568,
  749,
  767,
  591,
  656,
  754,
  678,
  741,
  573,
  514,
  636,
  616,
  702,
  724,
  586,
  676,
  662,
  714,
  758,
  643,
  733,
  646,
  584,
  679,
  639,
  613,
  719,
  769,
  557,
  700,
  726,
  723,
  668,
  653,
  699,
  592,
  555,
  675,
  604,
  760,
  626,
  759,
  561,
  651,
  746,
  750,
  774,
  744,
  634,
  590,
  735,
  709,
  776,
  734,
  579,
  742,
  572,
  753,
  710,
  621,
  575,
  647,
  569,
  607,
  689,
  772,
  627,
  640,
  690,
  583,
  628,
  785,
  674,
  698,
  641,
  683,
  717,
  784,
  727,
  558,
  687,
  657,
  594,
  706,
  707,
  556,
  577,
  654,
  703,
  619,
  630,
  775,
  771,
  781,
  783,
  688,
  638,
  582,
  745,
  624,
  747,
  777,
  566,
  667,
  554,
  606,
  614,
  739,
  686,
  782,
  680,
  695,
  682,
  599,
  732,
  666,
  635,
  780,
  644,
  551,
  622,
  588,
  738,
  737,
  762,
  671,
  625,
  755,
  663,
  757,
  580,
  715,
  576,
  655,
  565,
  712,
  713,
  642,
  596,
  730,
  691,
  736,
  615,
  605,
  731,
  650,
  673,
  779,
  563,
  587,
  681,
  729,
  645,
  649,
  725,
  728,
  684,
  553,
  571,
  704,
  567,
  778,
  766,
  708,
  685,
  677,
  748,
  608,
  664,
  618,
  585,
  692,
  601,
  693,
  696,
  581,
  552,
  761,
  593,
  711,
  560,
  763,
  665,
  720,
  660,
  570,
  633,
  694,
  600,
  756,
  740,
  765,
  617,
  623,
  743,
  770,
  602,
  718,
  652,
  751,
  764,
  578,
  603,
  721,
  768,
  609,
  637,
  598,
  669,
  794,
  812,
  807,
  801,
  810,
  816,
  811,
  822,
  805,
  787,
  826,
  800,
  793,
  825,
  808,
  791,
  786,
  806,
  792,
  809,
  819,
  798,
  797,
  828,
  827,
  813,
  789,
  795,
  799,
  788,
  821,
  804,
  803,
  817,
  824,
  818,
  790,
  823,
  796,
  815,
  814,
  802,
  833,
  831,
  830,
  834,
  836,
  835,
  832,
  837,
  840,
  857,
  858,
  841,
  856,
  855,
  846,
  852,
  848,
  854,
  845,
  851,
  847,
  859,
  842,
  839,
  850,
  849,
  843,
  853,
  838,
  863,
  861,
  860,
  866,
  862,
  867,
  868,
  864,
  865,
  869,
  884,
  907,
  878,
  882,
  910,
  883,
  886,
  894,
  914,
  888,
  920,
  913,
  909,
  893,
  911,
  921,
  904,
  924,
  899,
  902,
  874,
  903,
  908,
  916,
  887,
  925,
  901,
  918,
  900,
  905,
  926,
  896,
  890,
  895,
  871,
  922,
  917,
  906,
  885,
  892,
  872,
  891,
  915,
  898,
  897,
  880,
  870,
  923,
  881,
  912,
  889,
  877,
  919,
  876,
  875,
  873,
  879,
  929,
  937,
  930,
  931,
  928,
  943,
  939,
  940,
  935,
  932,
  938,
  941,
  942,
  936,
  944,
  933,
  927,
  934,
  1009,
  955,
  977,
  1007,
  1006,
  965,
  967,
  1002,
  968,
  969,
  1000,
  997,
  975,
  988,
  1016,
  1018,
  1015,
  963,
  966,
  1004,
  984,
  953,
  996,
  999,
  974,
  1010,
  973,
  991,
  1005,
  947,
  962,
  989,
  970,
  1001,
  1008,
  1017,
  1003,
  980,
  990,
  946,
  964,
  951,
  994,
  961,
  948,
  998,
  1011,
  979,
  1014,
  945,
  972,
  1012,
  958,
  957,
  959,
  982,
  987,
  981,
  986,
  978,
  976,
  ...])

In [5]:
positive_pairs = df[['UserID', 'ItemID']].values.tolist()

In [6]:
positive_pairs

[[0, 32],
 [0, 34],
 [0, 4],
 [0, 35],
 [0, 30],
 [0, 29],
 [0, 33],
 [0, 40],
 [0, 10],
 [0, 16],
 [0, 23],
 [0, 28],
 [0, 12],
 [0, 8],
 [0, 5],
 [0, 20],
 [0, 46],
 [0, 15],
 [0, 50],
 [0, 49],
 [0, 13],
 [0, 1],
 [0, 52],
 [0, 38],
 [0, 19],
 [0, 6],
 [0, 2],
 [0, 26],
 [0, 17],
 [0, 39],
 [0, 45],
 [0, 42],
 [0, 14],
 [0, 11],
 [0, 18],
 [0, 48],
 [0, 41],
 [0, 43],
 [0, 51],
 [0, 9],
 [0, 44],
 [0, 21],
 [0, 0],
 [0, 47],
 [0, 7],
 [0, 3],
 [0, 36],
 [0, 24],
 [0, 22],
 [0, 37],
 [0, 27],
 [0, 31],
 [1, 86],
 [1, 66],
 [1, 72],
 [1, 130],
 [1, 73],
 [1, 79],
 [1, 126],
 [1, 163],
 [1, 91],
 [1, 98],
 [1, 60],
 [1, 137],
 [1, 107],
 [1, 118],
 [1, 154],
 [1, 146],
 [1, 69],
 [1, 74],
 [1, 83],
 [1, 160],
 [1, 157],
 [1, 94],
 [1, 65],
 [1, 125],
 [1, 119],
 [1, 58],
 [1, 122],
 [1, 117],
 [1, 93],
 [1, 120],
 [1, 166],
 [1, 150],
 [1, 155],
 [1, 90],
 [1, 145],
 [1, 110],
 [1, 78],
 [1, 113],
 [1, 62],
 [1, 156],
 [1, 148],
 [1, 144],
 [1, 97],
 [1, 48],
 [1, 151],
 [1, 132],
 [1, 75],
 [1, 138],
 [1, 116],
 [1, 171],
 [1, 129],
 [1, 20],
 [1, 134],
 [1, 88],
 [1, 55],
 [1, 173],
 [1, 52],
 [1, 142],
 [1, 161],
 [1, 152],
 [1, 56],
 [1, 141],
 [1, 89],
 [1, 57],
 [1, 114],
 [1, 59],
 [1, 102],
 [1, 169],
 [1, 80],
 [1, 172],
 [1, 140],
 [1, 112],
 [1, 170],
 [1, 81],
 [1, 77],
 [1, 123],
 [1, 108],
 [1, 109],
 [1, 54],
 [1, 68],
 [1, 100],
 [1, 121],
 [1, 158],
 [1, 61],
 [1, 82],
 [1, 162],
 [1, 168],
 [1, 84],
 [1, 164],
 [1, 139],
 [1, 96],
 [1, 99],
 [1, 135],
 [1, 95],
 [1, 42],
 [1, 111],
 [1, 153],
 [1, 136],
 [1, 143],
 [1, 124],
 [1, 53],
 [1, 18],
 [1, 85],
 [1, 174],
 [1, 92],
 [1, 115],
 [1, 76],
 [1, 149],
 [1, 147],
 [1, 106],
 [1, 103],
 [1, 63],
 [1, 128],
 [1, 159],
 [1, 47],
 [1, 67],
 [1, 101],
 [1, 104],
 [1, 70],
 [1, 0],
 [1, 167],
 [1, 105],
 [1, 165],
 [1, 87],
 [1, 131],
 [1, 64],
 [1, 71],
 [1, 127],
 [2, 179],
 [2, 182],
 [2, 198],
 [2, 4],
 [2, 176],
 [2, 116],
 [2, 84],
 [2, 183],
 [2, 22],
 [2, 190],
 [2, 199],
 [2, 175],
 [2, 177],
 [2, 184],
 [2, 50],
 [2, 206],
 [2, 58],
 [2, 180],
 [2, 202],
 [2, 193],
 [2, 191],
 [2, 200],
 [2, 205],
 [2, 187],
 [2, 195],
 [2, 166],
 [2, 185],
 [2, 113],
 [2, 192],
 [2, 189],
 [2, 64],
 [2, 188],
 [2, 186],
 [2, 5],
 [2, 127],
 [2, 201],
 [2, 124],
 [2, 204],
 [2, 44],
 [2, 123],
 [2, 197],
 [2, 196],
 [2, 203],
 [2, 194],
 [2, 181],
 [2, 41],
 [2, 168],
 [2, 178],
 [2, 104],
 [2, 128],
 [3, 210],
 [3, 139],
 [3, 209],
 [3, 156],
 [3, 211],
 [3, 217],
 [3, 212],
 [3, 215],
 [3, 48],
 [3, 43],
 [3, 216],
 [3, 213],
 [3, 127],
 [3, 124],
 [3, 44],
 [3, 214],
 [3, 113],
 [3, 63],
 [3, 26],
 [3, 64],
 [4, 18],
 [4, 274],
 [4, 356],
 [4, 329],
 [4, 254],
 [4, 331],
 [4, 375],
 [4, 155],
 [4, 251],
 [4, 260],
 [4, 344],
 [4, 122],
 [4, 378],
 [4, 261],
 [4, 347],
 [4, 249],
 [4, 289],
 [4, 288],
 [4, 319],
 [4, 330],
 [4, 228],
 [4, 59],
 [4, 370],
 [4, 235],
 [4, 189],
 [4, 264],
 [4, 314],
 [4, 292],
 [4, 265],
 [4, 373],
 [4, 296],
 [4, 303],
 [4, 304],
 [4, 325],
 [4, 255],
 [4, 302],
 [4, 106],
 [4, 353],
 [4, 322],
 [4, 310],
 [4, 361],
 [4, 238],
 [4, 300],
 [4, 252],
 [4, 382],
 [4, 313],
 [4, 120],
 [4, 324],
 [4, 27],
 [4, 39],
 [4, 195],
 [4, 343],
 [4, 240],
 [4, 323],
 [4, 226],
 [4, 369],
 [4, 371],
 [4, 328],
 [4, 312],
 [4, 225],
 [4, 78],
 [4, 62],
 [4, 357],
 [4, 335],
 [4, 129],
 [4, 351],
 [4, 224],
 [4, 233],
 [4, 358],
 [4, 362],
 [4, 326],
 [4, 256],
 [4, 232],
 [4, 346],
 [4, 242],
 [4, 229],
 [4, 316],
 [4, 290],
 [4, 284],
 [4, 320],
 [4, 285],
 [4, 337],
 [4, 364],
 [4, 366],
 [4, 374],
 [4, 367],
 [4, 221],
 [4, 109],
 [4, 376],
 [4, 333],
 [4, 156],
 [4, 318],
 [4, 348],
 [4, 299],
 [4, 379],
 [4, 281],
 [4, 342],
 [4, 245],
 [4, 283],
 [4, 301],
 [4, 383],
 [4, 282],
 [4, 247],
 [4, 220],
 [4, 239],
 [4, 269],
 [4, 309],
 [4, 276],
 [4, 272],
 [4, 381],
 [4, 365],
 [4, 339],
 [4, 297],
 [4, 253],
 [4, 298],
 [4, 275],
 [4, 271],
 [4, 230],
 [4, 355],
 [4, 258],
 [4, 280],
 [4, 384],
 [4, 295],
 [4, 132],
 [4, 227],
 [4, 262],
 [4, 259],
 [4, 306],
 [4, 336],
 [4, 244],
 [4, 128],
 [4, 51],
 [4, 67],
 [4, 167],
 [4, 257],
 [4, 266],
 [4, 48],
 [4, 246],
 [4, 377],
 [4, 234],
 [4, 241],
 [4, 267],
 [4, 293],
 [4, 270],
 [4, 68],
 [4, 349],
 [4, 237],
 [4, 218],
 [4, 223],
 [4, 279],
 [4, 286],
 [4, 307],
 [4, 305],
 [4, 243],
 [4, 38],
 [4, 350],
 [4, 263],
 [4, 43],
 [4, 250],
 [4, 332],
 [4, 359],
 [4, 311],
 [4, 248],
 [4, 294],
 [4, 287],
 [4, 308],
 [4, 338],
 [4, 345],
 [4, 334],
 [4, 341],
 [4, 291],
 [4, 273],
 [4, 219],
 [4, 340],
 [4, 268],
 [4, 317],
 [4, 3],
 [4, 327],
 [4, 315],
 [4, 363],
 [4, 354],
 [4, 278],
 [4, 231],
 [4, 380],
 [4, 4],
 [4, 372],
 [4, 184],
 [4, 352],
 [4, 360],
 [4, 368],
 [4, 104],
 [4, 277],
 [4, 236],
 [4, 171],
 [4, 9],
 [4, 321],
 [4, 131],
 [5, 400],
 [5, 153],
 [5, 387],
 [5, 429],
 [5, 349],
 [5, 405],
 [5, 3],
 [5, 406],
 [5, 68],
 [5, 413],
 [5, 393],
 [5, 407],
 [5, 394],
 [5, 83],
 [5, 416],
 [5, 397],
 [5, 408],
 [5, 410],
 [5, 402],
 [5, 2],
 [5, 14],
 [5, 403],
 [5, 414],
 [5, 45],
 [5, 388],
 [5, 426],
 [5, 25],
 [5, 390],
 [5, 389],
 [5, 32],
 [5, 421],
 [5, 33],
 [5, 10],
 [5, 381],
 [5, 412],
 [5, 244],
 [5, 415],
 [5, 123],
 [5, 20],
 [5, 40],
 [5, 401],
 [5, 398],
 [5, 422],
 [5, 427],
 [5, 134],
 [5, 104],
 [5, 88],
 [5, 399],
 [5, 391],
 [5, 385],
 [5, 423],
 [5, 419],
 [5, 386],
 [5, 425],
 [5, 404],
 [5, 428],
 [5, 424],
 [5, 207],
 [5, 112],
 [5, 409],
 [5, 411],
 [5, 418],
 [5, 264],
 [5, 417],
 [5, 64],
 [5, 178],
 [5, 395],
 [5, 420],
 [5, 166],
 [5, 392],
 [6, 430],
 [6, 150],
 [6, 90],
 [6, 319],
 [6, 120],
 [6, 432],
 [6, 148],
 [6, 62],
 [6, 255],
 [6, 195],
 [6, 189],
 [6, 433],
 [6, 264],
 [6, 156],
 [6, 151],
 [6, 132],
 [6, 92],
 [6, 48],
 [6, 97],
 [6, 78],
 [6, 58],
 [6, 431],
 [6, 68],
 [6, 406],
 [6, 237],
 [6, 434],
 [6, 124],
 [6, 107],
 [6, 113],
 [6, 22],
 [7, 468],
 [7, 40],
 [7, 440],
 [7, 467],
 [7, 443],
 [7, 441],
 [7, 452],
 [7, 511],
 [7, 450],
 [7, 492],
 [7, 118],
 [7, 481],
 [7, 449],
 [7, 480],
 [7, 436],
 [7, 458],
 [7, 474],
 [7, 455],
 [7, 503],
 [7, 513],
 [7, 489],
 [7, 471],
 [7, 466],
 [7, 459],
 [7, 416],
 [7, 36],
 [7, 487],
 [7, 446],
 [7, 501],
 [7, 472],
 [7, 465],
 [7, 473],
 [7, 448],
 [7, 494],
 [7, 447],
 [7, 508],
 [7, 507],
 [7, 359],
 [7, 451],
 [7, 482],
 [7, 445],
 [7, 442],
 [7, 488],
 [7, 502],
 [7, 454],
 [7, 322],
 [7, 31],
 [7, 438],
 [7, 59],
 [7, 27],
 [7, 53],
 [7, 490],
 [7, 485],
 [7, 18],
 [7, 510],
 [7, 496],
 [7, 463],
 [7, 39],
 [7, 456],
 [7, 477],
 [7, 85],
 [7, 505],
 [7, 235],
 [7, 461],
 [7, 439],
 [7, 479],
 [7, 475],
 [7, 462],
 [7, 460],
 [7, 509],
 [7, 453],
 [7, 478],
 [7, 444],
 [7, 491],
 [7, 256],
 [7, 365],
 [7, 483],
 [7, 500],
 [7, 435],
 [7, 328],
 [7, 226],
 [7, 372],
 [7, 484],
 [7, 339],
 [7, 383],
 [7, 292],
 [7, 337],
 [7, 280],
 [7, 506],
 [7, 244],
 [7, 23],
 [7, 51],
 [7, 104],
 [7, 67],
 [7, 437],
 [7, 470],
 [7, 283],
 [7, 498],
 [7, 464],
 [7, 469],
 [7, 417],
 [7, 109],
 [7, 221],
 [7, 134],
 [7, 116],
 [7, 504],
 [7, 493],
 [7, 222],
 [7, 150],
 [7, 512],
 [7, 90],
 [7, 195],
 [7, 166],
 [7, 457],
 [7, 189],
 [7, 94],
 [7, 93],
 [7, 74],
 [7, 144],
 [7, 348],
 [7, 264],
 [7, 122],
 [7, 495],
 [7, 92],
 [7, 62],
 [7, 132],
 [7, 97],
 [7, 476],
 [7, 48],
 [7, 156],
 [7, 43],
 [7, 497],
 [7, 113],
 [7, 432],
 [7, 499],
 [7, 321],
 [7, 486],
 [7, 64],
 [8, 30],
 [8, 430],
 [8, 93],
 [8, 528],
 [8, 322],
 [8, 328],
 [8, 463],
 [8, 550],
 [8, 150],
 [8, 518],
 [8, 525],
 [8, 59],
 [8, 412],
 [8, 396],
 [8, 534],
 [8, 548],
 [8, 113],
 [8, 123],
 [8, 288],
 [8, 272],
 [8, 355],
 [8, 439],
 [8, 438],
 [8, 521],
 [8, 326],
 [8, 520],
 [8, 523],
 [8, 527],
 [8, 353],
 [8, 27],
 [8, 226],
 [8, 542],
 [8, 538],
 [8, 89],
 [8, 529],
 [8, 536],
 [8, 537],
 [8, 515],
 [8, 290],
 [8, 543],
 [8, 540],
 [8, 264],
 [8, 317],
 [8, 316],
 [8, 470],
 [8, 164],
 [8, 242],
 [8, 85],
 [8, 437],
 [8, 116],
 [8, 505],
 [8, 4],
 [8, 504],
 [8, 256],
 [8, 39],
 [8, 276],
 [8, 549],
 [8, 151],
 [8, 132],
 [8, 38],
 [8, 524],
 [8, 539],
 [8, 336],
 [8, 40],
 [8, 50],
 [8, 315],
 [8, 280],
 [8, 246],
 [8, 48],
 [8, 29],
 [8, 51],
 [8, 21],
 [8, 167],
 [8, 444],
 [8, 544],
 [8, 532],
 [8, 526],
 [8, 267],
 [8, 522],
 [8, 387],
 [8, 516],
 [8, 541],
 [8, 533],
 [8, 237],
 [8, 519],
 [8, 3],
 [8, 125],
 [8, 547],
 [8, 43],
 [8, 153],
 [8, 535],
 [8, 104],
 [8, 259],
 [8, 67],
 [8, 128],
 [8, 546],
 [8, 23],
 [8, 517],
 [8, 545],
 [8, 530],
 [8, 434],
 [8, 64],
 [8, 420],
 [8, 531],
 [8, 41],
 [9, 434],
 [9, 672],
 [9, 610],
 [9, 661],
 [9, 280],
 [9, 10],
 [9, 589],
 [9, 620],
 [9, 658],
 [9, 697],
 [9, 564],
 [9, 574],
 [9, 131],
 [9, 612],
 [9, 37],
 [9, 631],
 [9, 23],
 [9, 773],
 [9, 546],
 [9, 14],
 [9, 670],
 [9, 217],
 [9, 559],
 [9, 611],
 [9, 632],
 [9, 41],
 [9, 629],
 [9, 595],
 [9, 12],
 [9, 21],
 [9, 167],
 [9, 246],
 [9, 716],
 [9, 105],
 [9, 705],
 [9, 752],
 [9, 315],
 [9, 199],
 [9, 722],
 [9, 562],
 [9, 29],
 [9, 84],
 [9, 701],
 [9, 539],
 [9, 164],
 [9, 597],
 [9, 206],
 [9, 648],
 [9, 177],
 [9, 568],
 [9, 749],
 [9, 767],
 [9, 591],
 [9, 656],
 [9, 754],
 [9, 678],
 [9, 741],
 [9, 573],
 [9, 514],
 [9, 636],
 [9, 19],
 [9, 616],
 [9, 702],
 [9, 724],
 [9, 586],
 [9, 676],
 [9, 662],
 [9, 714],
 [9, 758],
 [9, 376],
 [9, 643],
 [9, 733],
 [9, 646],
 [9, 538],
 [9, 124],
 [9, 132],
 [9, 277],
 [9, 26],
 [9, 44],
 [9, 75],
 [9, 584],
 [9, 464],
 [9, 679],
 [9, 639],
 [9, 82],
 [9, 613],
 [9, 382],
 [9, 719],
 [9, 769],
 [9, 166],
 [9, 27],
 [9, 174],
 [9, 557],
 [9, 470],
 [9, 700],
 [9, 726],
 [9, 5],
 [9, 134],
 [9, 116],
 [9, 723],
 [9, 115],
 [9, 517],
 [9, 668],
 [9, 388],
 [9, 653],
 [9, 699],
 [9, 592],
 [9, 555],
 [9, 675],
 [9, 604],
 [9, 760],
 [9, 626],
 [9, 359],
 [9, 759],
 [9, 561],
 [9, 651],
 [9, 746],
 [9, 750],
 [9, 774],
 [9, 744],
 [9, 32],
 [9, 634],
 [9, 425],
 [9, 98],
 [9, 231],
 [9, 332],
 [9, 590],
 [9, 735],
 [9, 709],
 [9, 776],
 [9, 25],
 [9, 734],
 [9, 579],
 [9, 742],
 [9, 572],
 [9, 753],
 [9, 710],
 [9, 621],
 [9, 575],
 [9, 647],
 [9, 569],
 [9, 607],
 [9, 689],
 [9, 356],
 [9, 772],
 [9, 627],
 [9, 513],
 [9, 640],
 [9, 690],
 [9, 583],
 [9, 628],
 [9, 785],
 [9, 163],
 [9, 674],
 [9, 698],
 [9, 641],
 [9, 683],
 [9, 717],
 [9, 784],
 [9, 727],
 [9, 558],
 [9, 687],
 [9, 432],
 [9, 657],
 [9, 426],
 [9, 594],
 [9, 11],
 [9, 706],
 [9, 707],
 [9, 556],
 [9, 577],
 [9, 654],
 [9, 703],
 [9, 619],
 [9, 630],
 [9, 142],
 [9, 775],
 [9, 771],
 [9, 781],
 [9, 783],
 [9, 688],
 [9, 392],
 [9, 638],
 [9, 391],
 [9, 482],
 [9, 582],
 [9, 745],
 [9, 624],
 [9, 747],
 [9, 79],
 [9, 777],
 [9, 401],
 [9, 566],
 [9, 484],
 [9, 667],
 [9, 554],
 [9, 487],
 [9, 160],
 [9, 606],
 [9, 614],
 [9, 739],
 [9, 686],
 [9, 782],
 [9, 680],
 [9, 695],
 [9, 418],
 [9, 138],
 [9, 682],
 [9, 60],
 [9, 599],
 ...]

In [8]:
user_item_set = df.groupby('UserID')['ItemID'].apply(set).to_dict()
user_item_set

{0: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52},
 1: {0,
  18,
  20,
  42,
  47,
  48,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174},
 2: {4,
  5,
  22,
  41,
  44,
  50,
  58,
  64,
  84,
  104,
  113,
  116,
  123,
  124,
  127,
  128,
  166,
  168,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206},
 3: {26,
  43,
  44,
  48,
  63,
  64,
  113,
  124,
  127,
  139,
  156,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217},
 4: {3,
  4,
  9,
  18,
  27,
  38,
  39,
  43,
  48,
  51,
  59,
  62,
  67,
  68,
  78,
  104,
  106,
  109,
  120,
  122,
  128,
  129,
  131,
  132,
  155,
  156,
  167,
  171,
  184,
  189,
  195,
  218,
  219,
  220,
  221,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  300,
  301,
  302,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  375,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384},
 5: {2,
  3,
  10,
  14,
  20,
  25,
  32,
  33,
  40,
  45,
  64,
  68,
  83,
  88,
  104,
  112,
  123,
  134,
  153,
  166,
  178,
  207,
  244,
  264,
  349,
  381,
  385,
  386,
  387,
  388,
  389,
  390,
  391,
  392,
  393,
  394,
  395,
  397,
  398,
  399,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429},
 6: {22,
  48,
  58,
  62,
  68,
  78,
  90,
  92,
  97,
  107,
  113,
  120,
  124,
  132,
  148,
  150,
  151,
  156,
  189,
  195,
  237,
  255,
  264,
  319,
  406,
  430,
  431,
  432,
  433,
  434},
 7: {18,
  23,
  27,
  31,
  36,
  39,
  40,
  43,
  48,
  51,
  53,
  59,
  62,
  64,
  67,
  74,
  85,
  90,
  92,
  93,
  94,
  97,
  104,
  109,
  113,
  116,
  118,
  122,
  132,
  134,
  144,
  150,
  156,
  166,
  189,
  195,
  221,
  222,
  226,
  235,
  244,
  256,
  264,
  280,
  283,
  292,
  321,
  322,
  328,
  337,
  339,
  348,
  359,
  365,
  372,
  383,
  416,
  417,
  432,
  435,
  436,
  437,
  438,
  439,
  440,
  441,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  456,
  457,
  458,
  459,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499,
  500,
  501,
  502,
  503,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  513},
 8: {3,
  4,
  21,
  23,
  27,
  29,
  30,
  38,
  39,
  40,
  41,
  43,
  48,
  50,
  51,
  59,
  64,
  67,
  85,
  89,
  93,
  104,
  113,
  116,
  123,
  125,
  128,
  132,
  150,
  151,
  153,
  164,
  167,
  226,
  237,
  242,
  246,
  256,
  259,
  264,
  267,
  272,
  276,
  280,
  288,
  290,
  315,
  316,
  317,
  322,
  326,
  328,
  336,
  353,
  355,
  387,
  396,
  412,
  420,
  430,
  434,
  437,
  438,
  439,
  444,
  463,
  470,
  504,
  505,
  515,
  516,
  517,
  518,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550},
 9: {2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  17,
  19,
  20,
  21,
  22,
  23,
  25,
  26,
  27,
  29,
  30,
  32,
  33,
  37,
  38,
  39,
  40,
  41,
  44,
  45,
  50,
  53,
  58,
  60,
  64,
  75,
  76,
  77,
  79,
  82,
  83,
  84,
  86,
  87,
  89,
  92,
  96,
  97,
  98,
  104,
  105,
  108,
  110,
  111,
  112,
  113,
  115,
  116,
  119,
  123,
  124,
  127,
  131,
  132,
  134,
  138,
  139,
  142,
  149,
  153,
  158,
  159,
  160,
  163,
  164,
  166,
  167,
  171,
  174,
  177,
  179,
  182,
  183,
  184,
  186,
  187,
  189,
  199,
  200,
  202,
  203,
  205,
  206,
  207,
  209,
  211,
  213,
  215,
  217,
  231,
  236,
  246,
  273,
  277,
  280,
  283,
  288,
  290,
  292,
  312,
  315,
  317,
  322,
  331,
  332,
  335,
  338,
  356,
  359,
  376,
  377,
  382,
  386,
  388,
  390,
  391,
  392,
  396,
  401,
  414,
  418,
  419,
  420,
  424,
  425,
  426,
  432,
  434,
  435,
  438,
  443,
  452,
  462,
  464,
  470,
  482,
  484,
  487,
  499,
  505,
  513,
  514,
  515,
  517,
  528,
  531,
  534,
  535,
  538,
  539,
  546,
  547,
  551,
  552,
  553,
  554,
  555,
  556,
  557,
  558,
  559,
  560,
  561,
  562,
  563,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  579,
  580,
  581,
  582,
  583,
  584,
  585,
  586,
  587,
  588,
  589,
  590,
  591,
  592,
  593,
  594,
  595,
  596,
  597,
  598,
  599,
  600,
  601,
  602,
  603,
  604,
  605,
  606,
  607,
  608,
  609,
  610,
  611,
  612,
  613,
  614,
  615,
  616,
  617,
  618,
  619,
  620,
  621,
  622,
  623,
  624,
  625,
  626,
  627,
  628,
  629,
  630,
  631,
  632,
  633,
  634,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  648,
  649,
  650,
  651,
  652,
  653,
  654,
  655,
  656,
  657,
  658,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  667,
  668,
  669,
  670,
  671,
  672,
  673,
  674,
  675,
  676,
  677,
  678,
  679,
  680,
  681,
  682,
  683,
  684,
  685,
  686,
  687,
  688,
  689,
  690,
  691,
  692,
  693,
  694,
  695,
  696,
  697,
  698,
  699,
  700,
  701,
  702,
  703,
  704,
  705,
  706,
  707,
  708,
  709,
  710,
  711,
  712,
  713,
  714,
  715,
  716,
  717,
  718,
  719,
  720,
  721,
  722,
  723,
  724,
  725,
  726,
  727,
  728,
  729,
  730,
  731,
  732,
  733,
  734,
  735,
  736,
  737,
  738,
  739,
  740,
  741,
  742,
  743,
  744,
  745,
  746,
  747,
  748,
  749,
  750,
  751,
  752,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
  774,
  775,
  776,
  777,
  778,
  779,
  780,
  781,
  782,
  783,
  784,
  785},
 10: {4,
  5,
  7,
  13,
  15,
  18,
  20,
  38,
  49,
  51,
  67,
  74,
  84,
  88,
  89,
  92,
  104,
  106,
  113,
  116,
  123,
  127,
  128,
  129,
  134,
  138,
  156,
  164,
  167,
  170,
  171,
  177,
  179,
  184,
  198,
  206,
  242,
  259,
  269,
  280,
  290,
  291,
  304,
  305,
  307,
  317,
  331,
  336,
  343,
  352,
  355,
  358,
  371,
  374,
  382,
  383,
  396,
  418,
  432,
  438,
  444,
  454,
  457,
  464,
  465,
  466,
  502,
  506,
  509,
  521,
  524,
  529,
  530,
  533,
  534,
  542,
  547,
  566,
  567,
  579,
  600,
  614,
  635,
  638,
  642,
  668,
  683,
  686,
  701,
  703,
  732,
  745,
  756,
  771,
  786,
  787,
  788,
  789,
  790,
  791,
  792,
  793,
  794,
  795,
  796,
  797,
  798,
  799,
  800,
  801,
  802,
  803,
  804,
  805,
  806,
  807,
  808,
  809,
  810,
  811,
  812,
  813,
  814,
  815,
  816,
  817,
  818,
  819,
  821,
  822,
  823,
  824,
  825,
  826,
  827,
  828},
 11: {0,
  7,
  9,
  127,
  128,
  174,
  176,
  434,
  486,
  497,
  546,
  559,
  661,
  669,
  830,
  831,
  832,
  833,
  834,
  835,
  836,
  837},
 12: {5,
  6,
  9,
  23,
  26,
  44,
  48,
  58,
  60,
  62,
  64,
  72,
  78,
  83,
  84,
  86,
  90,
  92,
  97,
  98,
  112,
  113,
  117,
  119,
  123,
  124,
  126,
  127,
  128,
  132,
  145,
  146,
  148,
  150,
  151,
  154,
  155,
  156,
  160,
  163,
  166,
  167,
  186,
  189,
  191,
  193,
  200,
  202,
  204,
  205,
  218,
  244,
  259,
  277,
  300,
  319,
  437,
  500,
  528,
  540,
  546,
  558,
  573,
  575,
  578,
  586,
  587,
  605,
  619,
  622,
  630,
  636,
  643,
  644,
  646,
  647,
  673,
  702,
  717,
  718,
  733,
  741,
  758,
  767,
  783,
  836,
  838,
  839,
  840,
  841,
  842,
  843,
  845,
  846,
  847,
  848,
  849,
  850,
  851,
  852,
  853,
  854,
  855,
  856,
  857,
  858,
  859},
 13: {38,
  43,
  51,
  68,
  104,
  134,
  168,
  184,
  244,
  263,
  317,
  500,
  541,
  651,
  860,
  861,
  862,
  863,
  864,
  865,
  866,
  867,
  868,
  869},
 14: {0,
  3,
  18,
  20,
  23,
  38,
  44,
  48,
  58,
  59,
  62,
  64,
  67,
  68,
  69,
  72,
  73,
  75,
  78,
  83,
  85,
  90,
  92,
  93,
  94,
  104,
  107,
  113,
  116,
  117,
  122,
  124,
  127,
  128,
  132,
  134,
  137,
  148,
  149,
  151,
  155,
  156,
  160,
  163,
  164,
  166,
  167,
  168,
  171,
  175,
  178,
  179,
  184,
  185,
  186,
  187,
  189,
  195,
  202,
  205,
  226,
  231,
  240,
  242,
  244,
  246,
  251,
  255,
  259,
  263,
  274,
  280,
  290,
  292,
  305,
  316,
  317,
  324,
  327,
  343,
  349,
  352,
  357,
  368,
  372,
  374,
  376,
  382,
  387,
  390,
  398,
  406,
  416,
  444,
  445,
  452,
  454,
  456,
  461,
  462,
  463,
  470,
  478,
  501,
  507,
  509,
  514,
  516,
  517,
  518,
  520,
  521,
  522,
  523,
  524,
  530,
  533,
  534,
  541,
  567,
  571,
  586,
  593,
  622,
  651,
  656,
  657,
  685,
  690,
  711,
  713,
  729,
  731,
  732,
  753,
  788,
  793,
  800,
  808,
  825,
  850,
  860,
  866,
  870,
  871,
  872,
  873,
  874,
  875,
  876,
  877,
  878,
  879,
  880,
  881,
  882,
  883,
  884,
  885,
  886,
  887,
  888,
  889,
  890,
  891,
  892,
  893,
  894,
  895,
  896,
  897,
  898,
  899,
  900,
  901,
  902,
  903,
  904,
  905,
  906,
  907,
  908,
  909,
  910,
  911,
  912,
  913,
  914,
  915,
  916,
  917,
  918,
  919,
  920,
  921,
  922,
  923,
  924,
  925,
  926},
 15: {4,
  231,
  278,
  287,
  352,
  416,
  438,
  512,
  585,
  733,
  862,
  870,
  875,
  880,
  881,
  923,
  927,
  928,
  929,
  930,
  931,
  932,
  933,
  934,
  935,
  936,
  937,
  938,
  939,
  940,
  941,
  942,
  943,
  944},
 16: {0,
  4,
  10,
  20,
  21,
  22,
  23,
  26,
  38,
  44,
  48,
  50,
  59,
  62,
  64,
  67,
  68,
  75,
  77,
  78,
  85,
  90,
  92,
  96,
  97,
  104,
  110,
  112,
  113,
  116,
  117,
  121,
  123,
  124,
  128,
  132,
  134,
  141,
  144,
  149,
  151,
  155,
  156,
  160,
  167,
  171,
  189,
  209,
  211,
  214,
  217,
  229,
  237,
  240,
  244,
  251,
  256,
  259,
  269,
  275,
  276,
  277,
  280,
  284,
  288,
  290,
  293,
  294,
  315,
  322,
  324,
  338,
  348,
  349,
  351,
  359,
  372,
  376,
  381,
  387,
  431,
  432,
  444,
  465,
  467,
  468,
  479,
  493,
  515,
  519,
  520,
  523,
  525,
  528,
  529,
  531,
  533,
  538,
  544,
  550,
  586,
  591,
  603,
  605,
  611,
  615,
  619,
  628,
  643,
  646,
  655,
  662,
  663,
  664,
  666,
  676,
  702,
  714,
  724,
  733,
  737,
  740,
  743,
  748,
  754,
  767,
  783,
  833,
  847,
  853,
  856,
  858,
  859,
  864,
  896,
  917,
  945,
  946,
  947,
  948,
  949,
  950,
  951,
  952,
  953,
  954,
  955,
  956,
  957,
  958,
  959,
  960,
  961,
  962,
  963,
  964,
  965,
  966,
  967,
  968,
  969,
  970,
  971,
  972,
  973,
  974,
  975,
  976,
  977,
  978,
  979,
  980,
  981,
  982,
  983,
  984,
  985,
  986,
  987,
  988,
  989,
  990,
  991,
  992,
  993,
  994,
  995,
  996,
  997,
  998,
  999,
  1000,
  1001,
  1002,
  1003,
  1004,
  1005,
  1006,
  1007,
  1008,
  1009,
  1010,
  1011,
  1012,
  1013,
  1014,
  1015,
  1016,
  1017,
  1018},
 17: {0,
  4,
  5,
  8,
  9,
  10,
  17,
  19,
  23,
  25,
  26,
  27,
  30,
  33,
  34,
  35,
  37,
  40,
  42,
  44,
  45,
  46,
  47,
  48,
  49,
  52,
  53,
  57,
  58,
  59,
  60,
  62,
  64,
  68,
  72,
  75,
  79,
  82,
  83,
  84,
  86,
  89,
  91,
  92,
  93,
  97,
  98,
  103,
  104,
  110,
  118,
  123,
  124,
  125,
  126,
  127,
  130,
  139,
  144,
  148,
  153,
  155,
  156,
  160,
  163,
  164,
  166,
  168,
  180,
  186,
  187,
  188,
  189,
  191,
  193,
  196,
  197,
  200,
  202,
  205,
  207,
  208,
  210,
  213,
  214,
  215,
  216,
  217,
  218,
  222,
  237,
  242,
  244,
  246,
  259,
  264,
  283,
  284,
  287,
  303,
  316,
  317,
  323,
  331,
  336,
  337,
  343,
  353,
  364,
  375,
  381,
  389,
  390,
  401,
  406,
  412,
  416,
  417,
  424,
  435,
  438,
  462,
  465,
  467,
  468,
  470,
  474,
  484,
  495,
  500,
  510,
  514,
  531,
  541,
  542,
  551,
  558,
  566,
  568,
  569,
  573,
  575,
  577,
  580,
  587,
  588,
  590,
  591,
  593,
  596,
  608,
  609,
  612,
  620,
  622,
  624,
  628,
  632,
  647,
  651,
  656,
  664,
  666,
  671,
  673,
  678,
  682,
  685,
  700,
  711,
  713,
  714,
  717,
  719,
  720,
  728,
  731,
  733,
  734,
  740,
  741,
  749,
  754,
  767,
  770,
  775,
  776,
  792,
  794,
  796,
  798,
  836,
  842,
  843,
  845,
  846,
  848,
  854,
  857,
  858,
  884,
  891,
  893,
  896,
  907,
  920,
  921,
  922,
  923,
  929,
  950,
  1011,
  1016,
  1019,
  1020,
  1021,
  1022,
  1023,
  1024,
  1025,
  1026,
  1027,
  1028,
  1029,
  1030,
  1031,
  1032,
  1033,
  1034,
  1035,
  1036,
  1037,
  1038,
  1039,
  1040,
  1041,
  1042,
  1043,
  1044,
  1045,
  1046,
  1047,
  1048,
  1049,
  1050,
  1051,
  1052,
  1053,
  1054,
  1055,
  1056,
  1057,
  1058,
  1059,
  1060,
  1061,
  1062,
  1063,
  1064,
  1065,
  1066,
  1067,
  1068,
  1069,
  1070,
  1071,
  1072,
  1073,
  1074,
  1075,
  1076,
  1077,
  1078,
  1079,
  1080,
  1081,
  1082,
  1083,
  1084,
  1085,
  1086,
  1087,
  1088,
  1089,
  1090,
  1091,
  1092,
  1093,
  1094,
  1095,
  1096,
  1097,
  1098,
  1099,
  1100,
  1101,
  1102,
  1103,
  1104,
  1105,
  1106,
  1107,
  1108,
  1109},
 18: {0,
  4,
  5,
  8,
  9,
  10,
  13,
  16,
  20,
  21,
  22,
  23,
  26,
  33,
  37,
  38,
  40,
  41,
  43,
  44,
  46,
  48,
  50,
  58,
  60,
  64,
  65,
  78,
  83,
  84,
  88,
  92,
  94,
  96,
  97,
  104,
  113,
  116,
  117,
  119,
  120,
  124,
  125,
  127,
  128,
  131,
  132,
  137,
  146,
  147,
  148,
  151,
  155,
  163,
  167,
  171,
  175,
  181,
  186,
  189,
  192,
  195,
  198,
  205,
  207,
  209,
  210,
  212,
  213,
  214,
  216,
  217,
  218,
  231,
  237,
  242,
  243,
  251,
  263,
  264,
  268,
  273,
  277,
  293,
  305,
  315,
  317,
  319,
  320,
  340,
  349,
  352,
  376,
  381,
  387,
  390,
  417,
  431,
  432,
  435,
  438,
  440,
  468,
  469,
  486,
  493,
  505,
  512,
  515,
  517,
  519,
  528,
  535,
  538,
  541,
  547,
  551,
  554,
  580,
  584,
  586,
  587,
  588,
  590,
  594,
  596,
  600,
  608,
  609,
  612,
  615,
  619,
  630,
  632,
  635,
  641,
  643,
  644,
  646,
  663,
  669,
  671,
  688,
  711,
  713,
  714,
  728,
  732,
  733,
  740,
  741,
  748,
  754,
  755,
  756,
  760,
  762,
  780,
  786,
  790,
  839,
  843,
  848,
  866,
  868,
  869,
  873,
  877,
  884,
  895,
  898,
  910,
  911,
  923,
  930,
  931,
  932,
  935,
  939,
  942,
  949,
  970,
  975,
  994,
  996,
  1003,
  1004,
  1005,
  1008,
  1019,
  1022,
  1027,
  1040,
  1041,
  1046,
  1047,
  1057,
  1068,
  1069,
  1071,
  1080,
  1110,
  1111,
  1112,
  1113,
  1114,
  1115,
  1116,
  1117,
  1118,
  1119,
  1120,
  1121,
  1122,
  1123,
  1124,
  1125,
  1126,
  1127,
  1128,
  1129,
  1130,
  1131,
  1132,
  1133,
  1134,
  1135,
  1136,
  1137,
  1138,
  1139,
  1140,
  1141,
  1142,
  1143,
  1144,
  1145,
  1146,
  1147,
  1148,
  1149,
  1150,
  1151,
  1152,
  1153,
  1154,
  1155,
  1156,
  1157,
  1158,
  1159,
  1160,
  1161,
  1162},
 19: {48,
  58,
  68,
  92,
  97,
  104,
  132,
  151,
  155,
  214,
  217,
  242,
  246,
  272,
  290,
  387,
  406,
  644,
  840,
  909,
  949,
  1163,
  1164},
 20: {4,
  17,
  30,
  33,
  40,
  64,
  218,
  243,
  467,
  588,
  666,
  853,
  911,
  923,
  929,
  939,
  1165,
  1166,
  1168,
  1169,
  1170},
 21: {5,
  9,
  13,
  15,
  19,
  20,
  22,
  26,
  32,
  38,
  51,
  52,
  58,
  60,
  62,
  64,
  65,
  66,
  68,
  72,
  74,
  77,
  79,
  83,
  84,
  86,
  89,
  91,
  92,
  94,
  97,
  104,
  105,
  107,
  110,
  113,
  116,
  117,
  124,
  125,
  126,
  127,
  130,
  131,
  132,
  133,
  134,
  136,
  137,
  138,
  144,
  146,
  148,
  151,
  155,
  157,
  160,
  167,
  174,
  177,
  179,
  182,
  184,
  186,
  189,
  192,
  195,
  198,
  200,
  202,
  206,
  207,
  209,
  210,
  214,
  217,
  218,
  221,
  222,
  242,
  244,
  251,
  264,
  268,
  273,
  274,
  277,
  278,
  283,
  288,
  290,
  296,
  300,
  305,
  321,
  322,
  327,
  328,
  335,
  336,
  343,
  348,
  349,
  350,
  356,
  371,
  375,
  376,
  385,
  406,
  418,
  424,
  432,
  433,
  446,
  459,
  461,
  465,
  486,
  495,
  503,
  505,
  509,
  512,
  515,
  524,
  529,
  532,
  534,
  537,
  538,
  552,
  556,
  558,
  561,
  566,
  567,
  568,
  577,
  582,
  587,
  592,
  599,
  600,
  604,
  605,
  607,
  609,
  614,
  618,
  622,
  623,
  625,
  635,
  638,
  642,
  647,
  651,
  657,
  667,
  668,
  669,
  673,
  678,
  687,
  688,
  701,
  714,
  715,
  717,
  730,
  731,
  732,
  737,
  738,
  740,
  741,
  744,
  745,
  746,
  756,
  762,
  769,
  772,
  775,
  776,
  783,
  787,
  791,
  793,
  797,
  828,
  836,
  843,
  849,
  862,
  864,
  885,
  886,
  890,
  891,
  895,
  900,
  903,
  905,
  909,
  922,
  993,
  1000,
  1011,
  1014,
  1018,
  1027,
  1034,
  1042,
  1058,
  1063,
  1074,
  1075,
  1079,
  1087,
  1088,
  1094,
  1095,
  1101,
  1102,
  1120,
  1132,
  1138,
  1139,
  1140,
  1141,
  1149,
  1150,
  1153,
  1156,
  1165,
  1171,
  1172,
  1173,
  1174,
  1175,
  1176,
  1177,
  1178,
  1179,
  1180,
  1181,
  1182,
  1183,
  1184,
  1185,
  1186,
  1187,
  1188,
  1189,
  1190,
  1191,
  1192,
  1193,
  1194,
  1196,
  1197,
  1198,
  1199,
  1200,
  1201,
  1202,
  1203,
  1204,
  1205,
  1206,
  1207,
  1208,
  1209,
  1210,
  1211,
  1212,
  1213,
  1214,
  1215,
  1216,
  1217,
  1218,
  1219,
  1220,
  1221,
  1222,
  1223,
  1224,
  1225,
  1226,
  1227,
  1228,
  1229,
  1230},
 22: {1,
  4,
  10,
  19,
  21,
  26,
  29,
  38,
  40,
  43,
  44,
  51,
  58,
  59,
  60,
  62,
  67,
  68,
  75,
  78,
  85,
  86,
  88,
  90,
  93,
  96,
  97,
  98,
  104,
  107,
  112,
  113,
  116,
  119,
  124,
  128,
  132,
  134,
  136,
  138,
  141,
  145,
  147,
  151,
  155,
  160,
  164,
  184,
  189,
  202,
  204,
  209,
  210,
  211,
  214,
  217,
  221,
  229,
  237,
  242,
  244,

In [15]:
records = []

for user in tqdm(all_users, desc="Generating positive and negative pairs"):
    interacted = user_item_set[user]
    for item in all_items:
        label = 1 if item in interacted else 0
        records.append((user, item, label))

Generating positive and negative pairs: 100%|██████████| 6040/6040 [00:02<00:00, 2347.97it/s]

In [16]:
records

[(0, 32, 1),
 (0, 34, 1),
 (0, 4, 1),
 (0, 35, 1),
 (0, 30, 1),
 (0, 29, 1),
 (0, 33, 1),
 (0, 40, 1),
 (0, 10, 1),
 (0, 16, 1),
 (0, 23, 1),
 (0, 28, 1),
 (0, 12, 1),
 (0, 8, 1),
 (0, 5, 1),
 (0, 20, 1),
 (0, 46, 1),
 (0, 15, 1),
 (0, 50, 1),
 (0, 49, 1),
 (0, 13, 1),
 (0, 1, 1),
 (0, 52, 1),
 (0, 38, 1),
 (0, 19, 1),
 (0, 6, 1),
 (0, 2, 1),
 (0, 26, 1),
 (0, 17, 1),
 (0, 39, 1),
 (0, 45, 1),
 (0, 42, 1),
 (0, 14, 1),
 (0, 11, 1),
 (0, 18, 1),
 (0, 48, 1),
 (0, 41, 1),
 (0, 43, 1),
 (0, 51, 1),
 (0, 9, 1),
 (0, 44, 1),
 (0, 21, 1),
 (0, 0, 1),
 (0, 47, 1),
 (0, 7, 1),
 (0, 3, 1),
 (0, 36, 1),
 (0, 24, 1),
 (0, 22, 1),
 (0, 37, 1),
 (0, 27, 1),
 (0, 31, 1),
 (0, 86, 0),
 (0, 66, 0),
 (0, 72, 0),
 (0, 130, 0),
 (0, 73, 0),
 (0, 79, 0),
 (0, 126, 0),
 (0, 163, 0),
 (0, 91, 0),
 (0, 98, 0),
 (0, 60, 0),
 (0, 137, 0),
 (0, 107, 0),
 (0, 118, 0),
 (0, 154, 0),
 (0, 146, 0),
 (0, 69, 0),
 (0, 74, 0),
 (0, 83, 0),
 (0, 160, 0),
 (0, 157, 0),
 (0, 94, 0),
 (0, 65, 0),
 (0, 125, 0),
 (0, 119, 0),
 (0, 58, 0),
 (0, 122, 0),
 (0, 117, 0),
 (0, 93, 0),
 (0, 120, 0),
 (0, 166, 0),
 (0, 150, 0),
 (0, 155, 0),
 (0, 90, 0),
 (0, 145, 0),
 (0, 110, 0),
 (0, 78, 0),
 (0, 113, 0),
 (0, 62, 0),
 (0, 156, 0),
 (0, 148, 0),
 (0, 144, 0),
 (0, 97, 0),
 (0, 151, 0),
 (0, 132, 0),
 (0, 75, 0),
 (0, 138, 0),
 (0, 116, 0),
 (0, 171, 0),
 (0, 129, 0),
 (0, 134, 0),
 (0, 88, 0),
 (0, 55, 0),
 (0, 173, 0),
 (0, 142, 0),
 (0, 161, 0),
 (0, 152, 0),
 (0, 56, 0),
 (0, 141, 0),
 (0, 89, 0),
 (0, 57, 0),
 (0, 114, 0),
 (0, 59, 0),
 (0, 102, 0),
 (0, 169, 0),
 (0, 80, 0),
 (0, 172, 0),
 (0, 140, 0),
 (0, 112, 0),
 (0, 170, 0),
 (0, 81, 0),
 (0, 77, 0),
 (0, 123, 0),
 (0, 108, 0),
 (0, 109, 0),
 (0, 54, 0),
 (0, 68, 0),
 (0, 100, 0),
 (0, 121, 0),
 (0, 158, 0),
 (0, 61, 0),
 (0, 82, 0),
 (0, 162, 0),
 (0, 168, 0),
 (0, 84, 0),
 (0, 164, 0),
 (0, 139, 0),
 (0, 96, 0),
 (0, 99, 0),
 (0, 135, 0),
 (0, 95, 0),
 (0, 111, 0),
 (0, 153, 0),
 (0, 136, 0),
 (0, 143, 0),
 (0, 124, 0),
 (0, 53, 0),
 (0, 85, 0),
 (0, 174, 0),
 (0, 92, 0),
 (0, 115, 0),
 (0, 76, 0),
 (0, 149, 0),
 (0, 147, 0),
 (0, 106, 0),
 (0, 103, 0),
 (0, 63, 0),
 (0, 128, 0),
 (0, 159, 0),
 (0, 67, 0),
 (0, 101, 0),
 (0, 104, 0),
 (0, 70, 0),
 (0, 167, 0),
 (0, 105, 0),
 (0, 165, 0),
 (0, 87, 0),
 (0, 131, 0),
 (0, 64, 0),
 (0, 71, 0),
 (0, 127, 0),
 (0, 179, 0),
 (0, 182, 0),
 (0, 198, 0),
 (0, 176, 0),
 (0, 183, 0),
 (0, 190, 0),
 (0, 199, 0),
 (0, 175, 0),
 (0, 177, 0),
 (0, 184, 0),
 (0, 206, 0),
 (0, 180, 0),
 (0, 202, 0),
 (0, 193, 0),
 (0, 191, 0),
 (0, 200, 0),
 (0, 205, 0),
 (0, 187, 0),
 (0, 195, 0),
 (0, 185, 0),
 (0, 192, 0),
 (0, 189, 0),
 (0, 188, 0),
 (0, 186, 0),
 (0, 201, 0),
 (0, 204, 0),
 (0, 197, 0),
 (0, 196, 0),
 (0, 203, 0),
 (0, 194, 0),
 (0, 181, 0),
 (0, 178, 0),
 (0, 210, 0),
 (0, 209, 0),
 (0, 211, 0),
 (0, 217, 0),
 (0, 212, 0),
 (0, 215, 0),
 (0, 216, 0),
 (0, 213, 0),
 (0, 214, 0),
 (0, 274, 0),
 (0, 356, 0),
 (0, 329, 0),
 (0, 254, 0),
 (0, 331, 0),
 (0, 375, 0),
 (0, 251, 0),
 (0, 260, 0),
 (0, 344, 0),
 (0, 378, 0),
 (0, 261, 0),
 (0, 347, 0),
 (0, 249, 0),
 (0, 289, 0),
 (0, 288, 0),
 (0, 319, 0),
 (0, 330, 0),
 (0, 228, 0),
 (0, 370, 0),
 (0, 235, 0),
 (0, 264, 0),
 (0, 314, 0),
 (0, 292, 0),
 (0, 265, 0),
 (0, 373, 0),
 (0, 296, 0),
 (0, 303, 0),
 (0, 304, 0),
 (0, 325, 0),
 (0, 255, 0),
 (0, 302, 0),
 (0, 353, 0),
 (0, 322, 0),
 (0, 310, 0),
 (0, 361, 0),
 (0, 238, 0),
 (0, 300, 0),
 (0, 252, 0),
 (0, 382, 0),
 (0, 313, 0),
 (0, 324, 0),
 (0, 343, 0),
 (0, 240, 0),
 (0, 323, 0),
 (0, 226, 0),
 (0, 369, 0),
 (0, 371, 0),
 (0, 328, 0),
 (0, 312, 0),
 (0, 225, 0),
 (0, 357, 0),
 (0, 335, 0),
 (0, 351, 0),
 (0, 224, 0),
 (0, 233, 0),
 (0, 358, 0),
 (0, 362, 0),
 (0, 326, 0),
 (0, 256, 0),
 (0, 232, 0),
 (0, 346, 0),
 (0, 242, 0),
 (0, 229, 0),
 (0, 316, 0),
 (0, 290, 0),
 (0, 284, 0),
 (0, 320, 0),
 (0, 285, 0),
 (0, 337, 0),
 (0, 364, 0),
 (0, 366, 0),
 (0, 374, 0),
 (0, 367, 0),
 (0, 221, 0),
 (0, 376, 0),
 (0, 333, 0),
 (0, 318, 0),
 (0, 348, 0),
 (0, 299, 0),
 (0, 379, 0),
 (0, 281, 0),
 (0, 342, 0),
 (0, 245, 0),
 (0, 283, 0),
 (0, 301, 0),
 (0, 383, 0),
 (0, 282, 0),
 (0, 247, 0),
 (0, 220, 0),
 (0, 239, 0),
 (0, 269, 0),
 (0, 309, 0),
 (0, 276, 0),
 (0, 272, 0),
 (0, 381, 0),
 (0, 365, 0),
 (0, 339, 0),
 (0, 297, 0),
 (0, 253, 0),
 (0, 298, 0),
 (0, 275, 0),
 (0, 271, 0),
 (0, 230, 0),
 (0, 355, 0),
 (0, 258, 0),
 (0, 280, 0),
 (0, 384, 0),
 (0, 295, 0),
 (0, 227, 0),
 (0, 262, 0),
 (0, 259, 0),
 (0, 306, 0),
 (0, 336, 0),
 (0, 244, 0),
 (0, 257, 0),
 (0, 266, 0),
 (0, 246, 0),
 (0, 377, 0),
 (0, 234, 0),
 (0, 241, 0),
 (0, 267, 0),
 (0, 293, 0),
 (0, 270, 0),
 (0, 349, 0),
 (0, 237, 0),
 (0, 218, 0),
 (0, 223, 0),
 (0, 279, 0),
 (0, 286, 0),
 (0, 307, 0),
 (0, 305, 0),
 (0, 243, 0),
 (0, 350, 0),
 (0, 263, 0),
 (0, 250, 0),
 (0, 332, 0),
 (0, 359, 0),
 (0, 311, 0),
 (0, 248, 0),
 (0, 294, 0),
 (0, 287, 0),
 (0, 308, 0),
 (0, 338, 0),
 (0, 345, 0),
 (0, 334, 0),
 (0, 341, 0),
 (0, 291, 0),
 (0, 273, 0),
 (0, 219, 0),
 (0, 340, 0),
 (0, 268, 0),
 (0, 317, 0),
 (0, 327, 0),
 (0, 315, 0),
 (0, 363, 0),
 (0, 354, 0),
 (0, 278, 0),
 (0, 231, 0),
 (0, 380, 0),
 (0, 372, 0),
 (0, 352, 0),
 (0, 360, 0),
 (0, 368, 0),
 (0, 277, 0),
 (0, 236, 0),
 (0, 321, 0),
 (0, 400, 0),
 (0, 387, 0),
 (0, 429, 0),
 (0, 405, 0),
 (0, 406, 0),
 (0, 413, 0),
 (0, 393, 0),
 (0, 407, 0),
 (0, 394, 0),
 (0, 416, 0),
 (0, 397, 0),
 (0, 408, 0),
 (0, 410, 0),
 (0, 402, 0),
 (0, 403, 0),
 (0, 414, 0),
 (0, 388, 0),
 (0, 426, 0),
 (0, 25, 0),
 (0, 390, 0),
 (0, 389, 0),
 (0, 421, 0),
 (0, 412, 0),
 (0, 415, 0),
 (0, 401, 0),
 (0, 398, 0),
 (0, 422, 0),
 (0, 427, 0),
 (0, 399, 0),
 (0, 391, 0),
 (0, 385, 0),
 (0, 423, 0),
 (0, 419, 0),
 (0, 386, 0),
 (0, 425, 0),
 (0, 404, 0),
 (0, 428, 0),
 (0, 424, 0),
 (0, 207, 0),
 (0, 409, 0),
 (0, 411, 0),
 (0, 418, 0),
 (0, 417, 0),
 (0, 395, 0),
 (0, 420, 0),
 (0, 392, 0),
 (0, 430, 0),
 (0, 432, 0),
 (0, 433, 0),
 (0, 431, 0),
 (0, 434, 0),
 (0, 468, 0),
 (0, 440, 0),
 (0, 467, 0),
 (0, 443, 0),
 (0, 441, 0),
 (0, 452, 0),
 (0, 511, 0),
 (0, 450, 0),
 (0, 492, 0),
 (0, 481, 0),
 (0, 449, 0),
 (0, 480, 0),
 (0, 436, 0),
 (0, 458, 0),
 (0, 474, 0),
 (0, 455, 0),
 (0, 503, 0),
 (0, 513, 0),
 (0, 489, 0),
 (0, 471, 0),
 (0, 466, 0),
 (0, 459, 0),
 (0, 487, 0),
 (0, 446, 0),
 (0, 501, 0),
 (0, 472, 0),
 (0, 465, 0),
 (0, 473, 0),
 (0, 448, 0),
 (0, 494, 0),
 (0, 447, 0),
 (0, 508, 0),
 (0, 507, 0),
 (0, 451, 0),
 (0, 482, 0),
 (0, 445, 0),
 (0, 442, 0),
 (0, 488, 0),
 (0, 502, 0),
 (0, 454, 0),
 (0, 438, 0),
 (0, 490, 0),
 (0, 485, 0),
 (0, 510, 0),
 (0, 496, 0),
 (0, 463, 0),
 (0, 456, 0),
 (0, 477, 0),
 (0, 505, 0),
 (0, 461, 0),
 (0, 439, 0),
 (0, 479, 0),
 (0, 475, 0),
 (0, 462, 0),
 (0, 460, 0),
 (0, 509, 0),
 (0, 453, 0),
 (0, 478, 0),
 (0, 444, 0),
 (0, 491, 0),
 (0, 483, 0),
 (0, 500, 0),
 (0, 435, 0),
 (0, 484, 0),
 (0, 506, 0),
 (0, 437, 0),
 (0, 470, 0),
 (0, 498, 0),
 (0, 464, 0),
 (0, 469, 0),
 (0, 504, 0),
 (0, 493, 0),
 (0, 222, 0),
 (0, 512, 0),
 (0, 457, 0),
 (0, 495, 0),
 (0, 476, 0),
 (0, 497, 0),
 (0, 499, 0),
 (0, 486, 0),
 (0, 528, 0),
 (0, 550, 0),
 (0, 518, 0),
 (0, 525, 0),
 (0, 396, 0),
 (0, 534, 0),
 (0, 548, 0),
 (0, 521, 0),
 (0, 520, 0),
 (0, 523, 0),
 (0, 527, 0),
 (0, 542, 0),
 (0, 538, 0),
 (0, 529, 0),
 (0, 536, 0),
 (0, 537, 0),
 (0, 515, 0),
 (0, 543, 0),
 (0, 540, 0),
 (0, 549, 0),
 (0, 524, 0),
 (0, 539, 0),
 (0, 544, 0),
 (0, 532, 0),
 (0, 526, 0),
 (0, 522, 0),
 (0, 516, 0),
 (0, 541, 0),
 (0, 533, 0),
 (0, 519, 0),
 (0, 547, 0),
 (0, 535, 0),
 (0, 546, 0),
 (0, 517, 0),
 (0, 545, 0),
 (0, 530, 0),
 (0, 531, 0),
 (0, 672, 0),
 (0, 610, 0),
 (0, 661, 0),
 (0, 589, 0),
 (0, 620, 0),
 (0, 658, 0),
 (0, 697, 0),
 (0, 564, 0),
 (0, 574, 0),
 (0, 612, 0),
 (0, 631, 0),
 (0, 773, 0),
 (0, 670, 0),
 (0, 559, 0),
 (0, 611, 0),
 (0, 632, 0),
 (0, 629, 0),
 (0, 595, 0),
 (0, 716, 0),
 (0, 705, 0),
 (0, 752, 0),
 (0, 722, 0),
 (0, 562, 0),
 (0, 701, 0),
 (0, 597, 0),
 (0, 648, 0),
 (0, 568, 0),
 (0, 749, 0),
 (0, 767, 0),
 (0, 591, 0),
 (0, 656, 0),
 (0, 754, 0),
 (0, 678, 0),
 (0, 741, 0),
 (0, 573, 0),
 (0, 514, 0),
 (0, 636, 0),
 (0, 616, 0),
 (0, 702, 0),
 (0, 724, 0),
 (0, 586, 0),
 (0, 676, 0),
 (0, 662, 0),
 (0, 714, 0),
 (0, 758, 0),
 (0, 643, 0),
 (0, 733, 0),
 (0, 646, 0),
 (0, 584, 0),
 (0, 679, 0),
 (0, 639, 0),
 (0, 613, 0),
 (0, 719, 0),
 (0, 769, 0),
 (0, 557, 0),
 (0, 700, 0),
 (0, 726, 0),
 (0, 723, 0),
 (0, 668, 0),
 (0, 653, 0),
 (0, 699, 0),
 (0, 592, 0),
 (0, 555, 0),
 (0, 675, 0),
 (0, 604, 0),
 (0, 760, 0),
 (0, 626, 0),
 (0, 759, 0),
 (0, 561, 0),
 (0, 651, 0),
 (0, 746, 0),
 (0, 750, 0),
 (0, 774, 0),
 (0, 744, 0),
 (0, 634, 0),
 (0, 590, 0),
 (0, 735, 0),
 (0, 709, 0),
 (0, 776, 0),
 (0, 734, 0),
 (0, 579, 0),
 (0, 742, 0),
 (0, 572, 0),
 (0, 753, 0),
 (0, 710, 0),
 (0, 621, 0),
 (0, 575, 0),
 (0, 647, 0),
 (0, 569, 0),
 (0, 607, 0),
 (0, 689, 0),
 (0, 772, 0),
 (0, 627, 0),
 (0, 640, 0),
 (0, 690, 0),
 (0, 583, 0),
 (0, 628, 0),
 (0, 785, 0),
 (0, 674, 0),
 (0, 698, 0),
 (0, 641, 0),
 (0, 683, 0),
 (0, 717, 0),
 (0, 784, 0),
 (0, 727, 0),
 (0, 558, 0),
 (0, 687, 0),
 (0, 657, 0),
 (0, 594, 0),
 (0, 706, 0),
 (0, 707, 0),
 (0, 556, 0),
 (0, 577, 0),
 (0, 654, 0),
 (0, 703, 0),
 (0, 619, 0),
 (0, 630, 0),
 (0, 775, 0),
 (0, 771, 0),
 (0, 781, 0),
 (0, 783, 0),
 (0, 688, 0),
 (0, 638, 0),
 (0, 582, 0),
 (0, 745, 0),
 (0, 624, 0),
 (0, 747, 0),
 (0, 777, 0),
 (0, 566, 0),
 (0, 667, 0),
 (0, 554, 0),
 (0, 606, 0),
 (0, 614, 0),
 (0, 739, 0),
 (0, 686, 0),
 (0, 782, 0),
 (0, 680, 0),
 (0, 695, 0),
 (0, 682, 0),
 (0, 599, 0),
 (0, 732, 0),
 (0, 666, 0),
 (0, 635, 0),
 (0, 780, 0),
 (0, 644, 0),
 (0, 551, 0),
 (0, 622, 0),
 (0, 588, 0),
 (0, 738, 0),
 (0, 737, 0),
 (0, 762, 0),
 (0, 671, 0),
 (0, 625, 0),
 (0, 755, 0),
 (0, 663, 0),
 (0, 757, 0),
 (0, 580, 0),
 (0, 715, 0),
 (0, 576, 0),
 (0, 655, 0),
 (0, 565, 0),
 (0, 712, 0),
 (0, 713, 0),
 (0, 642, 0),
 (0, 596, 0),
 (0, 730, 0),
 (0, 691, 0),
 (0, 736, 0),
 (0, 615, 0),
 (0, 605, 0),
 (0, 731, 0),
 (0, 650, 0),
 (0, 673, 0),
 (0, 779, 0),
 (0, 563, 0),
 (0, 587, 0),
 (0, 681, 0),
 (0, 729, 0),
 (0, 645, 0),
 (0, 649, 0),
 (0, 725, 0),
 (0, 728, 0),
 (0, 684, 0),
 (0, 553, 0),
 (0, 571, 0),
 (0, 704, 0),
 (0, 567, 0),
 (0, 778, 0),
 (0, 766, 0),
 (0, 708, 0),
 (0, 685, 0),
 (0, 677, 0),
 (0, 748, 0),
 (0, 608, 0),
 (0, 664, 0),
 (0, 618, 0),
 (0, 585, 0),
 (0, 692, 0),
 (0, 601, 0),
 (0, 693, 0),
 (0, 696, 0),
 (0, 581, 0),
 (0, 552, 0),
 (0, 761, 0),
 (0, 593, 0),
 (0, 711, 0),
 (0, 560, 0),
 (0, 763, 0),
 (0, 665, 0),
 (0, 720, 0),
 (0, 660, 0),
 (0, 570, 0),
 (0, 633, 0),
 (0, 694, 0),
 (0, 600, 0),
 (0, 756, 0),
 (0, 740, 0),
 (0, 765, 0),
 (0, 617, 0),
 (0, 623, 0),
 (0, 743, 0),
 (0, 770, 0),
 (0, 602, 0),
 (0, 718, 0),
 (0, 652, 0),
 (0, 751, 0),
 (0, 764, 0),
 (0, 578, 0),
 (0, 603, 0),
 (0, 721, 0),
 (0, 768, 0),
 (0, 609, 0),
 (0, 637, 0),
 (0, 598, 0),
 (0, 669, 0),
 (0, 794, 0),
 (0, 812, 0),
 (0, 807, 0),
 (0, 801, 0),
 (0, 810, 0),
 (0, 816, 0),
 (0, 811, 0),
 (0, 822, 0),
 (0, 805, 0),
 (0, 787, 0),
 (0, 826, 0),
 (0, 800, 0),
 (0, 793, 0),
 (0, 825, 0),
 (0, 808, 0),
 (0, 791, 0),
 (0, 786, 0),
 (0, 806, 0),
 (0, 792, 0),
 (0, 809, 0),
 (0, 819, 0),
 (0, 798, 0),
 (0, 797, 0),
 (0, 828, 0),
 (0, 827, 0),
 (0, 813, 0),
 (0, 789, 0),
 (0, 795, 0),
 (0, 799, 0),
 (0, 788, 0),
 (0, 821, 0),
 (0, 804, 0),
 (0, 803, 0),
 (0, 817, 0),
 (0, 824, 0),
 (0, 818, 0),
 (0, 790, 0),
 (0, 823, 0),
 (0, 796, 0),
 (0, 815, 0),
 (0, 814, 0),
 (0, 802, 0),
 (0, 833, 0),
 (0, 831, 0),
 (0, 830, 0),
 (0, 834, 0),
 (0, 836, 0),
 (0, 835, 0),
 (0, 832, 0),
 (0, 837, 0),
 (0, 840, 0),
 (0, 857, 0),
 (0, 858, 0),
 (0, 841, 0),
 (0, 856, 0),
 (0, 855, 0),
 (0, 846, 0),
 (0, 852, 0),
 (0, 848, 0),
 (0, 854, 0),
 (0, 845, 0),
 (0, 851, 0),
 (0, 847, 0),
 (0, 859, 0),
 (0, 842, 0),
 (0, 839, 0),
 (0, 850, 0),
 (0, 849, 0),
 (0, 843, 0),
 (0, 853, 0),
 (0, 838, 0),
 (0, 863, 0),
 (0, 861, 0),
 (0, 860, 0),
 (0, 866, 0),
 (0, 862, 0),
 (0, 867, 0),
 (0, 868, 0),
 (0, 864, 0),
 (0, 865, 0),
 (0, 869, 0),
 (0, 884, 0),
 (0, 907, 0),
 (0, 878, 0),
 (0, 882, 0),
 (0, 910, 0),
 (0, 883, 0),
 (0, 886, 0),
 (0, 894, 0),
 (0, 914, 0),
 (0, 888, 0),
 (0, 920, 0),
 (0, 913, 0),
 (0, 909, 0),
 (0, 893, 0),
 (0, 911, 0),
 (0, 921, 0),
 (0, 904, 0),
 (0, 924, 0),
 (0, 899, 0),
 (0, 902, 0),
 (0, 874, 0),
 (0, 903, 0),
 (0, 908, 0),
 (0, 916, 0),
 (0, 887, 0),
 (0, 925, 0),
 (0, 901, 0),
 (0, 918, 0),
 (0, 900, 0),
 (0, 905, 0),
 (0, 926, 0),
 (0, 896, 0),
 (0, 890, 0),
 (0, 895, 0),
 (0, 871, 0),
 (0, 922, 0),
 (0, 917, 0),
 (0, 906, 0),
 (0, 885, 0),
 (0, 892, 0),
 (0, 872, 0),
 (0, 891, 0),
 (0, 915, 0),
 (0, 898, 0),
 (0, 897, 0),
 (0, 880, 0),
 (0, 870, 0),
 (0, 923, 0),
 (0, 881, 0),
 (0, 912, 0),
 (0, 889, 0),
 (0, 877, 0),
 (0, 919, 0),
 (0, 876, 0),
 (0, 875, 0),
 (0, 873, 0),
 (0, 879, 0),
 (0, 929, 0),
 (0, 937, 0),
 (0, 930, 0),
 (0, 931, 0),
 (0, 928, 0),
 (0, 943, 0),
 (0, 939, 0),
 (0, 940, 0),
 (0, 935, 0),
 (0, 932, 0),
 (0, 938, 0),
 (0, 941, 0),
 (0, 942, 0),
 (0, 936, 0),
 (0, 944, 0),
 (0, 933, 0),
 (0, 927, 0),
 (0, 934, 0),
 (0, 1009, 0),
 (0, 955, 0),
 (0, 977, 0),
 (0, 1007, 0),
 (0, 1006, 0),
 (0, 965, 0),
 (0, 967, 0),
 (0, 1002, 0),
 (0, 968, 0),
 (0, 969, 0),
 (0, 1000, 0),
 (0, 997, 0),
 (0, 975, 0),
 (0, 988, 0),
 (0, 1016, 0),
 (0, 1018, 0),
 (0, 1015, 0),
 (0, 963, 0),
 (0, 966, 0),
 (0, 1004, 0),
 (0, 984, 0),
 (0, 953, 0),
 (0, 996, 0),
 (0, 999, 0),
 (0, 974, 0),
 (0, 1010, 0),
 (0, 973, 0),
 (0, 991, 0),
 (0, 1005, 0),
 (0, 947, 0),
 (0, 962, 0),
 (0, 989, 0),
 (0, 970, 0),
 (0, 1001, 0),
 (0, 1008, 0),
 (0, 1017, 0),
 (0, 1003, 0),
 (0, 980, 0),
 (0, 990, 0),
 (0, 946, 0),
 (0, 964, 0),
 (0, 951, 0),
 (0, 994, 0),
 (0, 961, 0),
 (0, 948, 0),
 (0, 998, 0),
 (0, 1011, 0),
 (0, 979, 0),
 (0, 1014, 0),
 (0, 945, 0),
 (0, 972, 0),
 (0, 1012, 0),
 (0, 958, 0),
 (0, 957, 0),
 (0, 959, 0),
 (0, 982, 0),
 (0, 987, 0),
 (0, 981, 0),
 (0, 986, 0),
 (0, 978, 0),
 (0, 976, 0),
 ...]

In [17]:
pairs_df = pd.DataFrame(records, columns=['user', 'item', 'label'])
pairs_df

          user  item  label
0            0    32      1
1            0    34      1
2            0     4      1
3            0    35      1
4            0    30      1
...        ...   ...    ...
22372155  6039  3701      0
22372156  6039  3702      0
22372157  6039  3703      0
22372158  6039  3704      0
22372159  6039  3705      0

[22372160 rows x 3 columns]

In [18]:
pairs_df.to_csv("all_user_item_pairs.csv", index=False)

In [43]:
import pandas as pd
import numpy as np

df = pd.read_csv("/home/dhruv/Documents/NCF/NCF_Recommendation/NCF_Pytorch/Custom_User_centric_batch/all_user_item_pairs.csv")
df.head(5)

   user  item  label
0     0    32      1
1     0    34      1
2     0     4      1
3     0    35      1
4     0    30      1

In [44]:
df.shape

(22372160, 3)

In [45]:
df_1 = df[df.label == 1]
print(df_1.shape)
df_1

(994169, 3)

          user  item  label
0            0    32      1
1            0    34      1
2            0     4      1
3            0    35      1
4            0    30      1
...        ...   ...    ...
22371357  6039  2907      1
22371406  6039  2955      1
22371490  6039  3042      1
22371498  6039  3046      1
22371869  6039  3412      1

[994169 rows x 3 columns]

In [46]:
df_0 = df[df.label == 0]
print(df_0.shape)
df_0

(21377991, 3)

          user  item  label
52           0    86      0
53           0    66      0
54           0    72      0
55           0   130      0
56           0    73      0
...        ...   ...    ...
22372155  6039  3701      0
22372156  6039  3702      0
22372157  6039  3703      0
22372158  6039  3704      0
22372159  6039  3705      0

[21377991 rows x 3 columns]

In [47]:
import os, sys, time
import torch
from torch.utils.data import DataLoader, Dataset
import logging
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
class NcfEl2nTrainDataset(Dataset):
    def __init__(self, train_csv):
        
        self.train_df = pd.read_csv(train_csv)

        self.num_items = max(0, max(self.train_df["item"])+1)
        self.num_users = max(0, max(self.train_df["user"])+1)
        
        self.users, self.items, self.labels = self.train_df["user"], self.train_df["item"], self.train_df["label"]



    def __len__(self):
        return len(self.labels)
    
    def __getitem__(self, idx):
        return torch.tensor(self.users[idx], dtype=torch.long), torch.tensor(self.items[idx], dtype=torch.long), torch.tensor(self.labels[idx], dtype=torch.long)

In [49]:
train_data_object = NcfEl2nTrainDataset(train_csv="/home/dhruv/Documents/NCF/NCF_Recommendation/NCF_Pytorch/Custom_User_centric_batch/all_user_item_pairs.csv")

train_data_object

In [50]:
train_data_loader = DataLoader(train_data_object, 1024, shuffle=False)

In [51]:
os.getcwd()

'/home/dhruv/Documents/NCF/NCF_Recommendation/NCF_Pytorch/Custom_User_centric_batch'

In [52]:
sys.path.append("/home/dhruv/Documents/NCF/NCF_Recommendation/")

In [53]:
model1 = torch.load("/home/dhruv/Documents/NCF/NCF_Recommendation/NeuMF_Models/NeuMF_User_centric_El2n_model_3epoch/ml-1m_NeuMF_Batch_1024_epoch_3_10.pth", weights_only=False)

model2 = torch.load("/home/dhruv/Documents/NCF/NCF_Recommendation/NeuMF_Models/NeuMF_User_centric_El2n_model_5epoch/ml-1m_NeuMF_Batch_1024_epoch_5_10.pth", weights_only=False)

model3 = torch.load("/home/dhruv/Documents/NCF/NCF_Recommendation/NeuMF_Models/NeuMF_User_centric_El2n_model_10epoch/ml-1m_NeuMF_Batch_1024_epoch_10_10.pth", weights_only=False)


model1, model2, model3

(NeuMF(
   (user_embeddings_mf): Embedding(6040, 10)
   (item_embeddings_mf): Embedding(3706, 10)
   (user_embeddings_mlp): Embedding(6040, 16)
   (item_embeddings_mlp): Embedding(3706, 16)
   (mlp): Sequential(
     (0): Linear(in_features=32, out_features=16, bias=True)
     (1): ReLU()
     (2): Linear(in_features=16, out_features=8, bias=True)
     (3): ReLU()
   )
   (predict_layer): Linear(in_features=18, out_features=1, bias=True)
   (sigmoid): Sigmoid()
 ),
 NeuMF(
   (user_embeddings_mf): Embedding(6040, 10)
   (item_embeddings_mf): Embedding(3706, 10)
   (user_embeddings_mlp): Embedding(6040, 16)
   (item_embeddings_mlp): Embedding(3706, 16)
   (mlp): Sequential(
     (0): Linear(in_features=32, out_features=16, bias=True)
     (1): ReLU()
     (2): Linear(in_features=16, out_features=8, bias=True)
     (3): ReLU()
   )
   (predict_layer): Linear(in_features=18, out_features=1, bias=True)
   (sigmoid): Sigmoid()
 ),
 NeuMF(
   (user_embeddings_mf): Embedding(6040, 10)
   (item_embeddings_mf): Embedding(3706, 10)
   (user_embeddings_mlp): Embedding(6040, 16)
   (item_embeddings_mlp): Embedding(3706, 16)
   (mlp): Sequential(
     (0): Linear(in_features=32, out_features=16, bias=True)
     (1): ReLU()
     (2): Linear(in_features=16, out_features=8, bias=True)
     (3): ReLU()
   )
   (predict_layer): Linear(in_features=18, out_features=1, bias=True)
   (sigmoid): Sigmoid()
 ))

In [70]:
avg_outputs = []
output_model3 = []
output_model5 = []
output_model10 = []

for users, items, labels in train_data_loader:
    users = users
    items = items
    labels = labels.cpu().numpy()
    # print(users)
    # print(items)
    output1 = model1(users, items).detach().numpy()
    # print(output1)
    output2 = model2(users, items).detach().numpy()
    output3 = model3(users, items).detach().numpy()
    
    out1 = (output1 - labels)**2
    out2 = (output2 - labels)**2
    out3 = (output3 - labels)**2
    
    output_model3.extend(out1)
    output_model5.extend(out2)
    output_model10.extend(out3)
    
    avg_outputs.extend((out1+out2+out3)/3)
    
    # print((output1+output2+output3)/3)

In [71]:
df["output_model3"] = output_model3
df["output_model5"] = output_model5
df["output_model10"] = output_model10
df["avg_outputs"] = avg_outputs

In [72]:
df.to_csv("all_user_item_data_with_result.csv", index=False)

In [73]:
df.head()

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
0,0,32,1,0.942623,0.696994,0.713088,0.784235
1,0,34,1,0.872383,0.383507,0.127013,0.460968
2,0,4,1,0.705434,0.108107,0.343472,0.385671
3,0,35,1,0.962766,0.721432,0.633812,0.772670
4,0,30,1,0.950120,0.759607,0.680503,0.796743

In [88]:
df_sort = df.sort_values(by="avg_outputs", ascending=False)

In [89]:
total_rows = len(df)

In [90]:
total_rows

22372160

In [91]:
row_75 = total_rows*0.75

In [92]:
row_75

16779120.0

In [93]:
22372160 - 16779120

5593040

In [97]:
df_sort[df_sort["label"] == 0]

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
19876753,5366,1075,0,9.901767e-01,9.884929e-01,9.840487e-01,9.875728e-01
14161089,3823,737,0,9.754442e-01,9.983361e-01,9.883977e-01,9.873927e-01
6389471,1725,160,0,9.837795e-01,9.906949e-01,9.850145e-01,9.864963e-01
10282362,2776,126,0,9.813793e-01,9.947536e-01,9.817825e-01,9.859718e-01
13290785,3588,840,0,9.797814e-01,9.877301e-01,9.892504e-01,9.855873e-01
...,...,...,...,...,...,...,...
11930052,3220,3176,0,1.307209e-16,3.753227e-16,9.629750e-17,2.007804e-16
11930026,3220,3154,0,9.914720e-17,3.193206e-16,1.424010e-16,1.869563e-16
5511070,1487,3225,0,1.318920e-16,2.277750e-16,2.142916e-17,1.270321e-16
5511020,1487,3176,0,1.137301e-16,1.914842e-16,2.516627e-17,1.101268e-16
5510994,1487,3154,0,5.521216e-17,1.597879e-16,2.299795e-17,7.933266e-17

In [101]:
21377991*0.75

16033493.25

In [103]:
new_df = df_sort[df_sort["label"] == 0][:16033493+1]

In [104]:
new_df

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
19876753,5366,1075,0,9.901767e-01,9.884929e-01,9.840487e-01,9.875728e-01
14161089,3823,737,0,9.754442e-01,9.983361e-01,9.883977e-01,9.873927e-01
6389471,1725,160,0,9.837795e-01,9.906949e-01,9.850145e-01,9.864963e-01
10282362,2776,126,0,9.813793e-01,9.947536e-01,9.817825e-01,9.859718e-01
13290785,3588,840,0,9.797814e-01,9.877301e-01,9.892504e-01,9.855873e-01
...,...,...,...,...,...,...,...
13144814,3548,3025,0,8.084938e-07,1.368156e-08,2.096231e-08,2.810459e-07
14859310,4011,2578,0,7.060136e-07,4.338515e-08,9.373869e-08,2.810458e-07
1395649,376,2944,0,1.322120e-07,6.282704e-07,8.265497e-08,2.810458e-07
21635374,5841,339,0,2.255188e-07,4.718703e-07,1.457459e-07,2.810450e-07
1928262,520,2194,0,6.179138e-08,4.390959e-09,7.769525e-07,2.810449e-07

In [98]:
21377991*0.75

16033493.25

In [122]:
all_positive = df_sort[df_sort["label"] == 1]
all_positive

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
706533,190,2777,1,9.999997e-01,9.999989e-01,9.999993e-01,9.999993e-01
2714630,732,3308,1,9.999995e-01,9.999990e-01,9.999948e-01,9.999978e-01
2147838,579,3225,1,9.999996e-01,9.999945e-01,9.999992e-01,9.999978e-01
4618644,1246,3467,1,9.999992e-01,9.999975e-01,9.999960e-01,9.999976e-01
1947373,525,2777,1,9.999992e-01,9.999938e-01,9.999989e-01,9.999973e-01
...,...,...,...,...,...,...,...
16701544,4509,217,1,3.124745e-06,7.682282e-07,8.332765e-08,1.325434e-06
19875858,5366,189,1,1.532615e-06,4.065221e-07,1.887566e-06,1.275568e-06
12260434,3310,189,1,1.650502e-06,2.967262e-08,3.274863e-07,6.692202e-07
16701483,4509,124,1,7.482980e-07,3.286471e-07,5.932253e-07,5.567235e-07
12089946,3264,62,1,9.959253e-07,1.976612e-07,2.660688e-07,4.865518e-07

In [123]:
994169*0.75

745626.75

In [125]:
all_positive = all_positive[:745626]
all_positive

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
706533,190,2777,1,1.000000,0.999999,0.999999,0.999999
2714630,732,3308,1,1.000000,0.999999,0.999995,0.999998
2147838,579,3225,1,1.000000,0.999994,0.999999,0.999998
4618644,1246,3467,1,0.999999,0.999998,0.999996,0.999998
1947373,525,2777,1,0.999999,0.999994,0.999999,0.999997
...,...,...,...,...,...,...,...
8101359,2187,642,1,0.422617,0.040645,0.117355,0.193539
11776329,3179,1376,1,0.130756,0.075348,0.374513,0.193539
18557622,5010,573,1,0.480301,0.038426,0.061889,0.193539
15331736,4139,904,1,0.102105,0.374435,0.104072,0.193537
15013553,4053,1295,1,0.300130,0.024069,0.256410,0.193536

In [126]:
all_positive.sort_values("user",inplace=True)

/tmp/ipykernel_82436/1630673808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_positive.sort_values("user",inplace=True)

In [127]:
all_positive.reset_index(inplace=True, drop=True)

In [128]:
all_positive

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
0,0,30,1,0.950120,0.759607,0.680503,0.796743
1,0,37,1,0.920445,0.440455,0.562293,0.641064
2,0,19,1,0.909427,0.595991,0.807545,0.770988
3,0,4,1,0.705434,0.108107,0.343472,0.385671
4,0,31,1,0.976514,0.970144,0.949974,0.965544
...,...,...,...,...,...,...,...
745621,6039,1126,1,0.559346,0.376879,0.641982,0.526069
745622,6039,1235,1,0.338418,0.223428,0.195764,0.252536
745623,6039,461,1,0.725876,0.901293,0.909166,0.845445
745624,6039,2517,1,0.784274,0.732244,0.676122,0.730880
745625,6039,1933,1,0.536356,0.470198,0.223596,0.410050

In [130]:
all_positive.columns = ["UserID","ItemID", "label", "output_model3", "output_model5", "output_model10","avg_outputs"]
all_positive

,UserID,ItemID,label,output_model3,output_model5,output_model10,avg_outputs
0,0,30,1,0.950120,0.759607,0.680503,0.796743
1,0,37,1,0.920445,0.440455,0.562293,0.641064
2,0,19,1,0.909427,0.595991,0.807545,0.770988
3,0,4,1,0.705434,0.108107,0.343472,0.385671
4,0,31,1,0.976514,0.970144,0.949974,0.965544
...,...,...,...,...,...,...,...
745621,6039,1126,1,0.559346,0.376879,0.641982,0.526069
745622,6039,1235,1,0.338418,0.223428,0.195764,0.252536
745623,6039,461,1,0.725876,0.901293,0.909166,0.845445
745624,6039,2517,1,0.784274,0.732244,0.676122,0.730880
745625,6039,1933,1,0.536356,0.470198,0.223596,0.410050

In [132]:
d = pd.read_csv("/home/dhruv/Documents/NCF/NCF_Recommendation/NCF_Pytorch/train_data.csv")
d

        UserID  ItemID  Rating  Timestamp
0            0      32       4  978824330
1            0      34       4  978824330
2            0       4       5  978824291
3            0      35       4  978824291
4            0      30       4  978824291
...        ...     ...     ...        ...
994164    6039    1092       5  956703977
994165    6039      41       4  956703977
994166    6039     128       5  956703954
994167    6039     323       4  956703954
994168    6039     669       4  956703932

[994169 rows x 4 columns]

In [136]:
all_positive = all_positive.merge(d[['UserID', 'ItemID', 'Timestamp']], on=['UserID', 'ItemID'], how='left')

In [137]:
all_positive

,UserID,ItemID,label,output_model3,output_model5,output_model10,avg_outputs,Timestamp
0,0,30,1,0.950120,0.759607,0.680503,0.796743,978824291
1,0,37,1,0.920445,0.440455,0.562293,0.641064,978300055
2,0,19,1,0.909427,0.595991,0.807545,0.770988,978302039
3,0,4,1,0.705434,0.108107,0.343472,0.385671,978824291
4,0,31,1,0.976514,0.970144,0.949974,0.965544,978300019
...,...,...,...,...,...,...,...,...
745621,6039,1126,1,0.559346,0.376879,0.641982,0.526069,957717423
745622,6039,1235,1,0.338418,0.223428,0.195764,0.252536,956715288
745623,6039,461,1,0.725876,0.901293,0.909166,0.845445,997454486
745624,6039,2517,1,0.784274,0.732244,0.676122,0.730880,956704056
745625,6039,1933,1,0.536356,0.470198,0.223596,0.410050,956715910

In [138]:
all_positive.to_csv("El2n_positive.csv", index=False)

In [107]:
El2n_75_data = pd.concat([new_df,all_positive], axis=0)
El2n_75_data

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
19876753,5366,1075,0,9.901767e-01,9.884929e-01,9.840487e-01,9.875728e-01
14161089,3823,737,0,9.754442e-01,9.983361e-01,9.883977e-01,9.873927e-01
6389471,1725,160,0,9.837795e-01,9.906949e-01,9.850145e-01,9.864963e-01
10282362,2776,126,0,9.813793e-01,9.947536e-01,9.817825e-01,9.859718e-01
13290785,3588,840,0,9.797814e-01,9.877301e-01,9.892504e-01,9.855873e-01
...,...,...,...,...,...,...,...
16701544,4509,217,1,3.124745e-06,7.682282e-07,8.332765e-08,1.325434e-06
19875858,5366,189,1,1.532615e-06,4.065221e-07,1.887566e-06,1.275568e-06
12260434,3310,189,1,1.650502e-06,2.967262e-08,3.274863e-07,6.692202e-07
16701483,4509,124,1,7.482980e-07,3.286471e-07,5.932253e-07,5.567235e-07
12089946,3264,62,1,9.959253e-07,1.976612e-07,2.660688e-07,4.865518e-07

In [110]:
El2n_75_data.reset_index(inplace=True,drop=True)

In [113]:
El2n_75_data.drop(["index"], axis=1, inplace=True)

In [114]:
El2n_75_data

,user,item,label,output_model3,output_model5,output_model10,avg_outputs
0,5366,1075,0,9.901767e-01,9.884929e-01,9.840487e-01,9.875728e-01
1,3823,737,0,9.754442e-01,9.983361e-01,9.883977e-01,9.873927e-01
2,1725,160,0,9.837795e-01,9.906949e-01,9.850145e-01,9.864963e-01
3,2776,126,0,9.813793e-01,9.947536e-01,9.817825e-01,9.859718e-01
4,3588,840,0,9.797814e-01,9.877301e-01,9.892504e-01,9.855873e-01
...,...,...,...,...,...,...,...
17027658,4509,217,1,3.124745e-06,7.682282e-07,8.332765e-08,1.325434e-06
17027659,5366,189,1,1.532615e-06,4.065221e-07,1.887566e-06,1.275568e-06
17027660,3310,189,1,1.650502e-06,2.967262e-08,3.274863e-07,6.692202e-07
17027661,4509,124,1,7.482980e-07,3.286471e-07,5.932253e-07,5.567235e-07
17027662,3264,62,1,9.959253e-07,1.976612e-07,2.660688e-07,4.865518e-07

In [116]:
El2n_75_data.sort_values("user",inplace=True)

In [117]:
El2n_75_data.to_csv("El2n_75_data.csv", index=False)